#pragma once

#include <algorithm>
#include <cstdint>
#include <cmath>
#include <cstring>
#include <fstream>
#include <limits>
#include <string>
#include <unordered_map>
#include <vector>
#include "eiem_skin_binding.h"

// This is the native half of the EIEM package contract. It deliberately reads
// only the stable exchange format generated by AnimeStudio/Blender; it never
// attempts to deserialize Unity asset files in the game process.
struct EiemNativeSubMesh {
  int32_t topology;
  uint32_t indexStart;
  uint32_t indexCount;
  uint32_t baseVertex;
  uint32_t firstVertex;
  uint32_t vertexCount;
};

struct EiemNativeUvChannel {
  int32_t dimensions = 0;
  std::vector<Vector2> values2;
  std::vector<Vector3> values3;
  std::vector<Vector4> values4;
  bool Empty() const {
    return values2.empty() && values3.empty() && values4.empty();
  }
};

struct EiemNativeBlendShapeVertex {
  uint32_t index = 0;
  Vector3 vertex = {};
  Vector3 normal = {};
  Vector3 tangent = {};
};

struct EiemNativeBlendShapeFrame {
  std::string name;
  uint32_t firstVertex = 0;
  uint32_t vertexCount = 0;
  bool hasNormals = false;
  bool hasTangents = false;
  bool hasAdditionalNormals = false;
};

struct EiemNativeBlendShapeChannel {
  std::string name;
  uint32_t nameHash = 0;
  uint32_t frameIndex = 0;
  uint32_t frameCount = 0;
};

struct EiemNativeMeshDocument {
  std::string coordinateSpace;
  std::string source;
  std::string name;
  int32_t vertexCount = 0;
  std::vector<Vector3> vertices;
  std::vector<Vector3> normals;
  std::vector<Vector4> tangents;
  std::vector<Color> colors;
  EiemNativeUvChannel uvs[8];
  std::vector<uint32_t> indices;
  std::vector<EiemNativeSubMesh> subMeshes;
  std::vector<BoneWeight> skin;
  std::vector<Matrix4x4> bindPoses;
  std::vector<uint32_t> boneHashes;
  // EIEMESH v3 authoring metadata. Each entry identifies the shared skeleton
  // node addressed by each Mesh-local bone index. Each instance resolves
  // these paths against its shared skeleton; no new skeleton is created.
  std::vector<std::string> bonePaths;
  std::vector<EiemNativeBlendShapeVertex> blendShapeVertices;
  std::vector<EiemNativeBlendShapeFrame> blendShapeFrames;
  std::vector<EiemNativeBlendShapeChannel> blendShapeChannels;
  std::vector<float> blendShapeWeights;
};

// AnimeStudio's Unity asset reader and the native game both use Unity's
// Y-up, left-handed mesh basis.  The earlier experimental package marker
// called this Z-up and the runtime rotated vertices/bindposes on every load;
// that mixed the mesh basis with the live bone palette and produced twisting.
// The package already stores native mesh data and bindposes in the exact
// basis consumed by SkinnedMeshRenderer. Preserve the marker as metadata;
// there is no coordinate conversion at this runtime boundary.

class EiemNativeReader {
 public:
  explicit EiemNativeReader(const char *path) : input_(path, std::ios::binary) {}

  bool Good() const { return input_.good(); }
  bool End() { return input_.peek() == std::char_traits<char>::eof(); }

  bool Bytes(void *out, size_t count) {
    if (!out || count == 0) return count == 0;
    input_.read((char *)out, (std::streamsize)count);
    return input_.good();
  }

  template <typename T>
  bool Value(T *out) {
    return Bytes(out, sizeof(T));
  }

  bool String(std::string *out) {
    if (!out) return false;
    uint32_t length = 0;
    for (int shift = 0; shift <= 28; shift += 7) {
      uint8_t byte = 0;
      if (!Value(&byte)) return false;
      length |= (uint32_t)(byte & 0x7f) << shift;
      if (!(byte & 0x80)) break;
      if (shift == 28) return false;
    }
    if (length > 4 * 1024 * 1024) return false;
    out->resize(length);
    return !length || Bytes(out->data(), length);
  }

  bool Count(uint32_t *out, uint32_t maximum = 100000000) {
    int32_t value = 0;
    if (!Value(&value) || value < 0 || (uint32_t)value > maximum) return false;
    *out = (uint32_t)value;
    return true;
  }

  bool Skip(size_t count) {
    if (count > (size_t)(std::numeric_limits<std::streamoff>::max)()) return false;
    input_.seekg((std::streamoff)count, std::ios::cur);
    return input_.good();
  }

 private:
  std::ifstream input_;
};

static bool EiemReadFloatArray(EiemNativeReader &reader,
                               std::vector<float> *out) {
  uint32_t count = 0;
  if (!reader.Count(&count)) return false;
  out->resize(count);
  return !count || reader.Bytes(out->data(), (size_t)count * sizeof(float));
}

static bool EiemReadUvChannel(EiemNativeReader &reader,
                              EiemNativeUvChannel *out,
                              int32_t vertexCount) {
  std::vector<float> values;
  if (!out || !EiemReadFloatArray(reader, &values)) return false;
  if (values.empty()) return true;
  if (vertexCount <= 0 || values.size() % (size_t)vertexCount) return false;
  const size_t dimensions = values.size() / (size_t)vertexCount;
  out->dimensions = (int32_t)dimensions;
  if (dimensions == 2) {
    out->values2.resize((size_t)vertexCount);
    memcpy(out->values2.data(), values.data(), values.size() * sizeof(float));
  } else if (dimensions == 3) {
    out->values3.resize((size_t)vertexCount);
    memcpy(out->values3.data(), values.data(), values.size() * sizeof(float));
  } else if (dimensions == 4) {
    out->values4.resize((size_t)vertexCount);
    memcpy(out->values4.data(), values.data(), values.size() * sizeof(float));
  } else {
    return false;
  }
  return true;
}

template <typename T>
static bool EiemReadTypedFloatArray(EiemNativeReader &reader,
                                    std::vector<T> *out, uint32_t components,
                                    int32_t vertexCount) {
  std::vector<float> values;
  if (!EiemReadFloatArray(reader, &values)) return false;
  if (values.empty()) {
    out->clear();
    return true;
  }
  if (vertexCount < 0 || values.size() != (size_t)vertexCount * components ||
      sizeof(T) != components * sizeof(float))
    return false;
  out->resize((size_t)vertexCount);
  memcpy(out->data(), values.data(), values.size() * sizeof(float));
  return true;
}

static bool EiemReadBlendShapes(EiemNativeReader &reader,
                                EiemNativeMeshDocument *out) {
  uint32_t count = 0;
  if (!out || !reader.Count(&count, 10000000)) return false;
  out->blendShapeVertices.resize(count);
  for (auto &vertex : out->blendShapeVertices) {
    if (!reader.Value(&vertex.index) || !reader.Value(&vertex.vertex) ||
        !reader.Value(&vertex.normal) || !reader.Value(&vertex.tangent))
      return false;
  }
  if (!reader.Count(&count, 1000000)) return false;
  out->blendShapeFrames.resize(count);
  for (uint32_t i = 0; i < count; ++i) {
    auto &frame = out->blendShapeFrames[i];
    uint8_t hasNormals = 0, hasTangents = 0, hasAdditionalNormals = 0;
    if (!reader.String(&frame.name) || !reader.Value(&frame.firstVertex) ||
        !reader.Value(&frame.vertexCount) || !reader.Value(&hasNormals) ||
        !reader.Value(&hasTangents) || !reader.Value(&hasAdditionalNormals) ||
        (uint64_t)frame.firstVertex + frame.vertexCount >
            out->blendShapeVertices.size())
      return false;
    frame.hasNormals = hasNormals != 0;
    frame.hasTangents = hasTangents != 0;
    frame.hasAdditionalNormals = hasAdditionalNormals != 0;
  }
  if (!reader.Count(&count, 1000000)) return false;
  out->blendShapeChannels.resize(count);
  for (uint32_t i = 0; i < count; ++i) {
    auto &channel = out->blendShapeChannels[i];
    if (!reader.String(&channel.name) || !reader.Value(&channel.nameHash) ||
        !reader.Value(&channel.frameIndex) || !reader.Value(&channel.frameCount) ||
        (uint64_t)channel.frameIndex + channel.frameCount >
            out->blendShapeFrames.size())
      return false;
  }
  if (!EiemReadFloatArray(reader, &out->blendShapeWeights) ||
      out->blendShapeWeights.size() != out->blendShapeFrames.size() ||
      !reader.Count(&count, 10000000))
    return false;
  return reader.Skip((size_t)count * sizeof(float) * 3);
}

static bool EiemReadNativeMesh(const char *path, EiemNativeMeshDocument *out,
                               char *error, size_t errorSize) {
  if (error && errorSize) error[0] = '\0';
  if (!path || !out) return false;
  EiemNativeReader reader(path);
  char magic[8] = {};
  int32_t version = 0;
  if (!reader.Good() || !reader.Bytes(magic, sizeof(magic)) ||
      memcmp(magic, "EIEMESH\0", sizeof(magic)) != 0 || !reader.Value(&version) ||
      (version != 2 && version != 3) || !reader.String(&out->coordinateSpace) ||
      !reader.String(&out->source) || !reader.String(&out->name) ||
      !reader.Value(&out->vertexCount) || out->vertexCount < 0 ||
      out->vertexCount > 10000000 ||
      !EiemReadTypedFloatArray(reader, &out->vertices, 3, out->vertexCount) ||
      !EiemReadTypedFloatArray(reader, &out->normals, 3, out->vertexCount) ||
      !EiemReadTypedFloatArray(reader, &out->tangents, 4, out->vertexCount) ||
      !EiemReadTypedFloatArray(reader, &out->colors, 4, out->vertexCount)) {
    if (error) strncpy_s(error, errorSize, "Invalid EIEM mesh header or vertex channel", _TRUNCATE);
    return false;
  }
  for (size_t channel = 0; channel < _countof(out->uvs); ++channel) {
    if (!EiemReadUvChannel(reader, &out->uvs[channel], out->vertexCount)) {
      if (error) strncpy_s(error, errorSize, "Invalid EIEM UV channel", _TRUNCATE);
      return false;
    }
  }
  uint32_t count = 0;
  if (!reader.Count(&count) || count > 300000000) goto invalid;
  out->indices.resize(count);
  if (count && !reader.Bytes(out->indices.data(), (size_t)count * sizeof(uint32_t))) goto invalid;
  if (!reader.Count(&count, 1024)) goto invalid;
  out->subMeshes.resize(count);
  for (auto &subMesh : out->subMeshes) {
    if (!reader.Value(&subMesh.topology) || !reader.Value(&subMesh.indexStart) ||
        !reader.Value(&subMesh.indexCount) || !reader.Value(&subMesh.baseVertex) ||
        !reader.Value(&subMesh.firstVertex) || !reader.Value(&subMesh.vertexCount) ||
        subMesh.topology != 0 ||
        (uint64_t)subMesh.indexStart + subMesh.indexCount > out->indices.size())
      goto invalid;
  }
  if (!reader.Count(&count, 10000000)) goto invalid;
  out->skin.resize(count);
  if (count && !reader.Bytes(out->skin.data(), (size_t)count * sizeof(BoneWeight))) goto invalid;
  if (!out->skin.empty() && out->skin.size() != out->vertices.size()) goto invalid;
  if (!reader.Count(&count, 10000000)) goto invalid;
  out->bindPoses.resize(count);
  if (count && !reader.Bytes(out->bindPoses.data(), (size_t)count * sizeof(Matrix4x4))) goto invalid;
  if (!reader.Count(&count, 10000000)) goto invalid;
  out->boneHashes.resize(count);
  if (count && !reader.Bytes(out->boneHashes.data(), (size_t)count * sizeof(uint32_t))) goto invalid;
  if (version >= 3) {
    if (!reader.Count(&count, 1000000)) goto invalid;
    out->bonePaths.resize(count);
    for (auto &path : out->bonePaths) {
      if (!reader.String(&path)) goto invalid;
    }
    if (!out->bonePaths.empty() &&
        out->bonePaths.size() != out->bindPoses.size())
      goto invalid;
  }
  if (!EiemReadBlendShapes(reader, out) || !reader.End()) goto invalid;
  if (out->vertices.size() != (size_t)out->vertexCount || out->subMeshes.empty()) goto invalid;
  return true;

invalid:
  if (error) strncpy_s(error, errorSize, "Invalid or unsupported EIEM mesh payload", _TRUNCATE);
  return false;
}

static void *s_eiemMeshClass = nullptr;
static void *s_eiemVector2Class = nullptr;
static void *s_eiemVector3Class = nullptr;
static void *s_eiemVector4Class = nullptr;
static void *s_eiemColorClass = nullptr;
static void *s_eiemBoneWeightClass = nullptr;
static void *s_eiemMatrix4x4Class = nullptr;
static void *s_eiemInt32Class = nullptr;
static void *s_eiemObjectClass = nullptr;
static void *s_eiemObjectSetName = nullptr;
static void *s_eiemMeshCtor = nullptr;
static void *s_eiemMeshSetIndexFormat = nullptr;
static void *s_eiemMeshSetVertices = nullptr;
static void *s_eiemMeshGetVertices = nullptr;
static void *s_eiemMeshSetNormals = nullptr;
static void *s_eiemMeshSetTangents = nullptr;
static void *s_eiemMeshSetColors = nullptr;
static void *s_eiemMeshSetUVs2 = nullptr;
static void *s_eiemMeshSetUVs3 = nullptr;
static void *s_eiemMeshSetUVs4 = nullptr;
static void *s_eiemMeshSetSubMeshCount = nullptr;
static void *s_eiemMeshSetTriangles = nullptr;
static void *s_eiemMeshSetBoneWeights = nullptr;
static void *s_eiemMeshSetBindPoses = nullptr;
static void *s_eiemMeshUploadMeshData = nullptr;
static void *s_eiemMeshGetBoneWeights = nullptr;
static void *s_eiemMeshGetBindPoses = nullptr;
static void *s_eiemMeshAddBlendShapeFrame = nullptr;
static void *s_eiemMeshGetBlendShapeFrameCount = nullptr;
static void *s_eiemMaterialClass = nullptr;
static void *s_eiemRendererClass = nullptr;
static void *s_eiemResourceManagerClass = nullptr;
static void *s_eiemProxyHandleClass = nullptr;
static void *s_eiemMaterialCtorCopy = nullptr;
static void *s_eiemMaterialSetFloat = nullptr;
static void *s_eiemMaterialSetInt = nullptr;
static void *s_eiemMaterialSetColor = nullptr;
static void *s_eiemMaterialSetTextureScale = nullptr;
static void *s_eiemMaterialSetTextureOffset = nullptr;
static void *s_eiemRendererSetSharedMaterials = nullptr;
static void *s_eiemResourceManagerLoad = nullptr;
static void *s_eiemProxyLoadImmediate = nullptr;
static void *s_eiemProxyGet = nullptr;
static void *s_eiemTexture2DClass = nullptr;
static void *s_eiemTextureClass = nullptr;
static void *s_eiemImageConversionClass = nullptr;
static void *s_eiemByteClass = nullptr;
static void *s_eiemTexture2DCtor = nullptr;
static void *s_eiemImageLoad = nullptr;
static void *s_eiemTextureSetFilterMode = nullptr;
static void *s_eiemTextureSetWrapMode = nullptr;
static void *s_eiemTextureSetAnisoLevel = nullptr;
static void *s_eiemTextureSetMipMapBias = nullptr;

static void EiemLogManagedValueTypeLayout(const char *label, void *klass,
                                          size_t nativeSize) {
  if (!klass) {
    Log("[DEBUG-SKIN-LAYOUT] type=%s class=<null> nativeSize=%zu",
        label ? label : "unknown", nativeSize);
    return;
  }
  uint32_t alignment = 0;
  const int32_t managedSize = il2cpp_class_value_size
                                  ? il2cpp_class_value_size(klass, &alignment)
                                  : -1;
  Log("[DEBUG-SKIN-LAYOUT] type=%s class=%p nativeSize=%zu managedSize=%d alignment=%u",
      label ? label : "unknown", klass, nativeSize, managedSize, alignment);
  if (!il2cpp_class_get_fields || !il2cpp_field_get_name ||
      !il2cpp_field_get_offset)
    return;
  void *iterator = nullptr;
  void *field = nullptr;
  while ((field = il2cpp_class_get_fields(klass, &iterator))) {
    const char *fieldName = il2cpp_field_get_name(field);
    void *fieldType = il2cpp_field_get_type ? il2cpp_field_get_type(field) : nullptr;
    const char *typeName = fieldType && il2cpp_type_get_name
                               ? il2cpp_type_get_name(fieldType)
                               : nullptr;
    Log("[DEBUG-SKIN-LAYOUT] type=%s field=%s fieldType=%s offset=0x%zX",
        label ? label : "unknown", fieldName ? fieldName : "<unknown>",
        typeName ? typeName : "<unknown>", il2cpp_field_get_offset(field));
  }
}
static void *s_eiemMaterialSetTexture = nullptr;
static void *s_eiemMaterialGetTexture = nullptr;
// Updated by the game's own resource-load hook. Using that live manager keeps
// source= paths inside the original VFS/decryption/manifest pipeline.
static void *s_eiemResourceManagerInstance = nullptr;
// UnityEngine.Object construction and most Unity property calls must happen
// on the thread that initialized the IL2CPP backend. Resource hooks can also
// run on worker threads; those calls are left to the Renderer fallback there.
static DWORD s_eiemUnityThreadId = 0;

// Mesh, material and texture resources are generated on demand. Keep their
// managed wrappers rooted for reuse; native lifetime must still be checked.
// Snapshot copies share the root, so Unity validity calls run outside locks.
struct EiemObjectResourceCacheEntry {
  char modPath[MAX_PATH] = {};
  char section[96] = {};
  uint64_t fileStamp = 0;
  std::shared_ptr<const EiemSkinIdentity> skin;
  EiemUnityRef object;
};

static SRWLOCK s_eiemMaterialResourceCacheLock = SRWLOCK_INIT;
static std::vector<EiemObjectResourceCacheEntry> s_eiemMaterialResourceCache;
static SRWLOCK s_eiemTextureResourceCacheLock = SRWLOCK_INIT;
static std::vector<EiemObjectResourceCacheEntry> s_eiemTextureResourceCache;

static uint64_t EiemMeshResourceFileStamp(const char *path);
static uint64_t EiemTextureDependencyStamp(const EiemModResource &resource,
                                           uint64_t fileStamp);

// true + null = cache miss; false = cannot safely determine validity.
// Unknown is not a miss: do not mutate the cache or publish a guessed object.
static bool EiemFindCachedObject(
    std::vector<EiemObjectResourceCacheEntry> &cache, SRWLOCK *lock,
    const char *modPath, const char *section, uint64_t fileStamp,
    void **out, char *error, size_t errorSize,
    std::shared_ptr<const EiemSkinIdentity> *skin = nullptr) {
  if (out) *out = nullptr;
  if (skin) skin->reset();
  if (!EiemOnUnityThread()) {
    if (error) strncpy_s(error, errorSize, "Resource cache requires Unity thread", _TRUNCATE);
    return false;
  }
  for (;;) {
    EiemObjectResourceCacheEntry snapshot;
    bool found = false;
    AcquireSRWLockShared(lock);
    for (const auto &entry : cache) {
      if (_stricmp(entry.modPath, modPath) == 0 &&
          _stricmp(entry.section, section) == 0) {
        snapshot = entry;
        found = true;
        break;
      }
    }
    ReleaseSRWLockShared(lock);
    if (!found) return true;
    const int status = snapshot.fileStamp == fileStamp ? snapshot.object.Status() : 0;
    if (status < 0) {
      if (error) strncpy_s(error, errorSize, "Cached resource native validity is unknown", _TRUNCATE);
      return false;
    }
    if (status == 1) {
      if (out) *out = snapshot.object.Target();
      if (skin) *skin = snapshot.skin;
      return true;
    }
    // Remove only this snapshot. A concurrent cache clear/store cannot make
    // us erase a newer entry; the shared root also prevents handle-ID reuse.
    AcquireSRWLockExclusive(lock);
    cache.erase(std::remove_if(cache.begin(), cache.end(), [&](const auto &entry) {
      return entry.object.Handle() == snapshot.object.Handle() &&
             _stricmp(entry.modPath, modPath) == 0 && _stricmp(entry.section, section) == 0;
    }), cache.end());
    ReleaseSRWLockExclusive(lock);
    Log("[MOD-CACHE] evicted mod=%s section=%s reason=%s", modPath, section,
        snapshot.fileStamp == fileStamp ? "native expired" : "file changed");
  }
}

static bool EiemCacheObject(std::vector<EiemObjectResourceCacheEntry> &cache,
                            SRWLOCK *lock, const char *modPath,
                            const char *section, uint64_t fileStamp,
                            void *object, char *error, size_t errorSize,
                            std::shared_ptr<const EiemSkinIdentity> skin = nullptr) {
  if (EiemNativeObjectStatus(object) != 1) {
    if (error) strncpy_s(error, errorSize, "Generated resource is not natively valid", _TRUNCATE);
    return false;
  }
  EiemObjectResourceCacheEntry entry = {};
  strncpy_s(entry.modPath, sizeof(entry.modPath), modPath, _TRUNCATE);
  strncpy_s(entry.section, sizeof(entry.section), section, _TRUNCATE);
  entry.fileStamp = fileStamp;
  entry.skin = std::move(skin);
  entry.object = EiemUnityRef::Capture(object, false);
  if (!entry.object) {
    if (error) strncpy_s(error, errorSize, "Unable to retain generated resource", _TRUNCATE);
    return false;
  }
  AcquireSRWLockExclusive(lock);
  for (auto it = cache.begin(); it != cache.end();) {
    if (_stricmp(it->modPath, modPath) == 0 &&
        _stricmp(it->section, section) == 0) {
      it = cache.erase(it);
    } else {
      ++it;
    }
  }
  cache.push_back(entry);
  ReleaseSRWLockExclusive(lock);
  return true;
}

static void *EiemFindMethodWithParamTypes(void *klass, const char *name,
                                           const char *const *types,
                                           int count) {
  if (!klass || !name || !types || count < 0) return nullptr;
  void *iterator = nullptr;
  void *method = nullptr;
  while ((method = il2cpp_class_get_methods(klass, &iterator))) {
    const char *methodName = il2cpp_method_get_name(method);
    if (!methodName || strcmp(methodName, name) != 0 ||
        (int)il2cpp_method_get_param_count(method) != count)
      continue;
    bool matches = true;
    for (int index = 0; index < count; ++index) {
      void *param = il2cpp_method_get_param(method, index);
      const char *typeName = param && il2cpp_type_get_name
                                 ? il2cpp_type_get_name(param)
                                 : nullptr;
      if (!typeName || strcmp(typeName, types[index]) != 0) {
        matches = false;
        break;
      }
    }
    if (matches) return method;
  }
  return nullptr;
}

static void *EiemFindMethodWithReturnType(void *klass, const char *name,
                                           const char *returnType,
                                           int paramCount) {
  if (!klass || !name || !returnType) return nullptr;
  void *iterator = nullptr;
  void *method = nullptr;
  while ((method = il2cpp_class_get_methods(klass, &iterator))) {
    const char *methodName = il2cpp_method_get_name(method);
    if (!methodName || strcmp(methodName, name) != 0 ||
        (int)il2cpp_method_get_param_count(method) != paramCount)
      continue;
    void *type = il2cpp_method_get_return_type(method);
    const char *typeName = type && il2cpp_type_get_name ? il2cpp_type_get_name(type) : nullptr;
    if (typeName && strcmp(typeName, returnType) == 0) return method;
  }
  return nullptr;
}

static void EiemResolveResourceBackend(void **assemblies, size_t assemblyCount) {
  s_eiemMeshClass = FindClass("UnityEngine", "Mesh", assemblies, assemblyCount);
  s_eiemVector2Class = FindClass("UnityEngine", "Vector2", assemblies, assemblyCount);
  s_eiemVector3Class = FindClass("UnityEngine", "Vector3", assemblies, assemblyCount);
  s_eiemVector4Class = FindClass("UnityEngine", "Vector4", assemblies, assemblyCount);
  s_eiemColorClass = FindClass("UnityEngine", "Color", assemblies, assemblyCount);
  s_eiemBoneWeightClass = FindClass("UnityEngine", "BoneWeight", assemblies, assemblyCount);
  s_eiemMatrix4x4Class = FindClass("UnityEngine", "Matrix4x4", assemblies, assemblyCount);
  s_eiemInt32Class = FindClass("System", "Int32", assemblies, assemblyCount);
  s_eiemObjectClass = FindClass("UnityEngine", "Object", assemblies, assemblyCount);
  s_eiemMaterialClass = FindClass("UnityEngine", "Material", assemblies, assemblyCount);
  s_eiemRendererClass = FindClass("UnityEngine", "Renderer", assemblies, assemblyCount);
  s_eiemResourceManagerClass = FindClass("Beyond.Resource.Runtime", "BundleResourceManager",
                                         assemblies, assemblyCount);
  s_eiemProxyHandleClass = FindClass("Beyond.Resource", "FAssetProxyHandle",
                                     assemblies, assemblyCount);
  s_eiemTexture2DClass = FindClass("UnityEngine", "Texture2D", assemblies, assemblyCount);
  s_eiemTextureClass = FindClass("UnityEngine", "Texture", assemblies, assemblyCount);
  s_eiemImageConversionClass = FindClass("UnityEngine", "ImageConversion",
                                         assemblies, assemblyCount);
  s_eiemByteClass = FindClass("System", "Byte", assemblies, assemblyCount);
  if (s_eiemObjectClass) {
    s_eiemObjectSetName = FindMethod(s_eiemObjectClass, "set_name", 1);
  }
  if (s_eiemMeshClass) {
    s_eiemMeshCtor = FindMethod(s_eiemMeshClass, ".ctor", 0);
    s_eiemMeshSetIndexFormat = FindMethod(s_eiemMeshClass, "set_indexFormat", 1);
    s_eiemMeshSetVertices = FindMethod(s_eiemMeshClass, "set_vertices", 1);
    s_eiemMeshGetVertices = FindMethod(s_eiemMeshClass, "get_vertices", 0);
    s_eiemMeshSetNormals = FindMethod(s_eiemMeshClass, "set_normals", 1);
    s_eiemMeshSetTangents = FindMethod(s_eiemMeshClass, "set_tangents", 1);
    s_eiemMeshSetColors = FindMethod(s_eiemMeshClass, "set_colors", 1);
    static const char *const setUvsTypes[] = {
        "System.Int32", "UnityEngine.Vector2[]"};
    static const char *const setUvs3Types[] = {
        "System.Int32", "UnityEngine.Vector3[]"};
    static const char *const setUvs4Types[] = {
        "System.Int32", "UnityEngine.Vector4[]"};
    static const char *const setTrianglesTypes[] = {
        "System.Int32[]", "System.Int32"};
    s_eiemMeshSetUVs2 = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetUVs", setUvsTypes, _countof(setUvsTypes));
    s_eiemMeshSetUVs3 = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetUVs", setUvs3Types, _countof(setUvs3Types));
    s_eiemMeshSetUVs4 = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetUVs", setUvs4Types, _countof(setUvs4Types));
    s_eiemMeshSetSubMeshCount = FindMethod(s_eiemMeshClass, "set_subMeshCount", 1);
    s_eiemMeshSetTriangles = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetTriangles", setTrianglesTypes,
        _countof(setTrianglesTypes));
    s_eiemMeshSetBoneWeights = FindMethod(s_eiemMeshClass, "set_boneWeights", 1);
    s_eiemMeshSetBindPoses = FindMethod(s_eiemMeshClass, "set_bindposes", 1);
    s_eiemMeshUploadMeshData = FindMethod(s_eiemMeshClass, "UploadMeshData", 1);
    s_eiemMeshGetBoneWeights = FindMethod(s_eiemMeshClass, "get_boneWeights", 0);
    s_eiemMeshGetBindPoses = FindMethod(s_eiemMeshClass, "get_bindposes", 0);
    static const char *const blendShapeTypes[] = {
        "System.String", "System.Single", "UnityEngine.Vector3[]",
        "UnityEngine.Vector3[]", "UnityEngine.Vector3[]"};
    s_eiemMeshAddBlendShapeFrame = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "AddBlendShapeFrame", blendShapeTypes,
        _countof(blendShapeTypes));
    g_mesh_get_blendShapeCount = FindMethod(s_eiemMeshClass, "get_blendShapeCount", 0);
    g_mesh_GetBlendShapeName = FindMethod(s_eiemMeshClass, "GetBlendShapeName", 1);
    s_eiemMeshGetBlendShapeFrameCount = FindMethod(s_eiemMeshClass, "GetBlendShapeFrameCount", 1);
    g_mesh_recalculateBounds = FindMethod(s_eiemMeshClass, "RecalculateBounds", 0);
  }
  if (s_eiemMaterialClass) {
    static const char *const materialCopyCtorTypes[] = {"UnityEngine.Material"};
    static const char *const stringFloatTypes[] = {"System.String", "System.Single"};
    static const char *const stringIntTypes[] = {"System.String", "System.Int32"};
    static const char *const stringColorTypes[] = {"System.String", "UnityEngine.Color"};
    static const char *const stringTextureTypes[] = {"System.String", "UnityEngine.Texture"};
    static const char *const stringTypes[] = {"System.String"};
    static const char *const stringVector2Types[] = {"System.String", "UnityEngine.Vector2"};
    s_eiemMaterialCtorCopy = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, ".ctor", materialCopyCtorTypes,
        _countof(materialCopyCtorTypes));
    s_eiemMaterialSetFloat = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetFloat", stringFloatTypes, _countof(stringFloatTypes));
    s_eiemMaterialSetInt = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetInt", stringIntTypes, _countof(stringIntTypes));
    s_eiemMaterialSetColor = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetColor", stringColorTypes, _countof(stringColorTypes));
    s_eiemMaterialSetTexture = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetTexture", stringTextureTypes, _countof(stringTextureTypes));
    s_eiemMaterialGetTexture = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "GetTexture", stringTypes, _countof(stringTypes));
    s_eiemMaterialSetTextureScale = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetTextureScale", stringVector2Types,
        _countof(stringVector2Types));
    s_eiemMaterialSetTextureOffset = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetTextureOffset", stringVector2Types,
        _countof(stringVector2Types));
  }
  if (s_eiemRendererClass)
    s_eiemRendererSetSharedMaterials = FindMethod(s_eiemRendererClass, "set_sharedMaterials", 1);
  if (s_eiemResourceManagerClass) {
    static const char *const loadTypes[] = {
        "System.String", "System.Type", "Beyond.Resource.RootCategory"};
    s_eiemResourceManagerLoad = EiemFindMethodWithParamTypes(
        s_eiemResourceManagerClass, "Load", loadTypes, _countof(loadTypes));
  }
  if (s_eiemProxyHandleClass) {
    s_eiemProxyLoadImmediate = FindMethod(s_eiemProxyHandleClass, "LoadImmediate", 0);
    s_eiemProxyGet = EiemFindMethodWithReturnType(
        s_eiemProxyHandleClass, "Get", "UnityEngine.Object", 0);
  }
  if (s_eiemTexture2DClass) {
    static const char *const textureCtorTypes[] = {
        "System.Int32", "System.Int32", "UnityEngine.TextureFormat",
        "System.Boolean", "System.Boolean"};
    s_eiemTexture2DCtor = EiemFindMethodWithParamTypes(
        s_eiemTexture2DClass, ".ctor", textureCtorTypes,
        _countof(textureCtorTypes));
  }
  if (s_eiemTextureClass) {
    static const char *const filterTypes[] = {"UnityEngine.FilterMode"};
    static const char *const wrapTypes[] = {"UnityEngine.TextureWrapMode"};
    static const char *const intTypes[] = {"System.Int32"};
    static const char *const floatTypes[] = {"System.Single"};
    s_eiemTextureSetFilterMode = EiemFindMethodWithParamTypes(
        s_eiemTextureClass, "set_filterMode", filterTypes, _countof(filterTypes));
    s_eiemTextureSetWrapMode = EiemFindMethodWithParamTypes(
        s_eiemTextureClass, "set_wrapMode", wrapTypes, _countof(wrapTypes));
    s_eiemTextureSetAnisoLevel = EiemFindMethodWithParamTypes(
        s_eiemTextureClass, "set_anisoLevel", intTypes, _countof(intTypes));
    s_eiemTextureSetMipMapBias = EiemFindMethodWithParamTypes(
        s_eiemTextureClass, "set_mipMapBias", floatTypes, _countof(floatTypes));
  }
  if (s_eiemImageConversionClass) {
    static const char *const loadImageTypes[] = {
        "UnityEngine.Texture2D", "System.Byte[]", "System.Boolean"};
    s_eiemImageLoad = EiemFindMethodWithParamTypes(
        s_eiemImageConversionClass, "LoadImage", loadImageTypes,
        _countof(loadImageTypes));
  }
  Log("[MOD] Mesh backend: setName=%p ctor=%p vertices=%p/%p normals=%p tangents=%p uv=%p triangles=%p bones=%p/%p bindposes=%p/%p upload=%p blendShapes=%p bounds=%p",
      s_eiemObjectSetName, s_eiemMeshCtor, s_eiemMeshSetVertices,
      s_eiemMeshGetVertices, s_eiemMeshSetNormals, s_eiemMeshSetTangents,
      s_eiemMeshSetUVs2, s_eiemMeshSetTriangles,
      s_eiemMeshSetBoneWeights, s_eiemMeshGetBoneWeights,
      s_eiemMeshSetBindPoses, s_eiemMeshGetBindPoses,
      s_eiemMeshUploadMeshData,
      s_eiemMeshAddBlendShapeFrame,
      g_mesh_recalculateBounds);
  Log("[MOD] Material backend: load=%p immediate=%p get=%p clone=%p setMaterials=%p scale=%p offset=%p",
      s_eiemResourceManagerLoad, s_eiemProxyLoadImmediate, s_eiemProxyGet,
      s_eiemMaterialCtorCopy, s_eiemRendererSetSharedMaterials,
      s_eiemMaterialSetTextureScale, s_eiemMaterialSetTextureOffset);
  Log("[MOD] Texture backend: texture2D=%p imageConversion=%p loadImage=%p setTexture=%p getTexture=%p ctor=%p filter=%p wrap=%p aniso=%p bias=%p",
      s_eiemTexture2DClass, s_eiemImageConversionClass, s_eiemImageLoad,
      s_eiemMaterialSetTexture, s_eiemMaterialGetTexture, s_eiemTexture2DCtor,
      s_eiemTextureSetFilterMode, s_eiemTextureSetWrapMode,
      s_eiemTextureSetAnisoLevel, s_eiemTextureSetMipMapBias);
  EiemLogManagedValueTypeLayout("UnityEngine.BoneWeight",
                                s_eiemBoneWeightClass, sizeof(BoneWeight));
  EiemLogManagedValueTypeLayout("UnityEngine.Matrix4x4",
                                s_eiemMatrix4x4Class, sizeof(Matrix4x4));
}

template <typename T>
static void *EiemMakeValueArray(void *klass, const std::vector<T> &values) {
  if (!klass || values.empty()) return nullptr;
  void *array = il2cpp_array_new(klass, values.size());
  if (array) memcpy((char *)array + IL2CPP_ARRAY_DATA, values.data(),
                    values.size() * sizeof(T));
  return array;
}

static int32_t EiemBackendManagedArrayLength(void *array) {
  __try {
    const uintptr_t count = array ? *(uintptr_t *)((char *)array + 24) : 0;
    return count <= INT32_MAX ? (int32_t)count : -1;
  } __except (1) {
    return -1;
  }
}

template <typename T>
static bool EiemCopyBackendArray(void *array, std::vector<T> *out) {
  if (!array || !out) return false;
  const int32_t count = EiemBackendManagedArrayLength(array);
  if (count < 0 || count > 10000000) return false;
  out->resize((size_t)count);
  if (count)
    memcpy(out->data(), (char *)array + IL2CPP_ARRAY_DATA,
           (size_t)count * sizeof(T));
  return true;
}

static void *EiemBackendInvokeNoThrow(void *method, void *self);

template <typename T>
static void EiemLogArrayDiff(const char *kind, const std::vector<T> &payload,
                             const std::vector<T> &runtime,
                             size_t compareCount = SIZE_MAX) {
  const size_t count = (std::min)((std::min)(payload.size(), runtime.size()),
                                  compareCount);
  size_t byteMismatch = 0;
  float maxAbs = 0.0f;
  const float *left = reinterpret_cast<const float *>(payload.data());
  const float *right = reinterpret_cast<const float *>(runtime.data());
  const size_t floatsPerItem = sizeof(T) / sizeof(float);
  for (size_t item = 0; item < count; ++item) {
    if (memcmp(&payload[item], &runtime[item], sizeof(T)) != 0) ++byteMismatch;
    for (size_t component = 0; component < floatsPerItem; ++component) {
      const float delta = std::fabs(left[item * floatsPerItem + component] -
                                    right[item * floatsPerItem + component]);
      if (delta > maxAbs) maxAbs = delta;
    }
  }
  Log("[DEBUG-SKIN-DIFF] kind=%s payload=%zu runtime=%zu compared=%zu "
      "byteMismatch=%zu maxAbs=%.9g",
      kind ? kind : "unknown", payload.size(), runtime.size(), count,
      byteMismatch, maxAbs);
}

static void EiemLogBoneWeightDiff(const std::vector<BoneWeight> &payload,
                                  const std::vector<BoneWeight> &runtime,
                                  size_t compareCount = SIZE_MAX) {
  const size_t count = (std::min)((std::min)(payload.size(), runtime.size()),
                                  compareCount);
  size_t weightMismatch = 0;
  size_t indexMismatch = 0;
  size_t firstWeightMismatch = SIZE_MAX;
  size_t firstIndexMismatch = SIZE_MAX;
  float maxWeightDelta = 0.0f;
  for (size_t item = 0; item < count; ++item) {
    const float *leftWeights = &payload[item].weight0;
    const float *rightWeights = &runtime[item].weight0;
    const int *leftIndices = &payload[item].boneIndex0;
    const int *rightIndices = &runtime[item].boneIndex0;
    bool weightsDiffer = false;
    bool indicesDiffer = false;
    for (size_t component = 0; component < 4; ++component) {
      const float delta =
          std::fabs(leftWeights[component] - rightWeights[component]);
      if (delta != 0.0f) weightsDiffer = true;
      if (delta > maxWeightDelta) maxWeightDelta = delta;
      if (leftIndices[component] != rightIndices[component])
        indicesDiffer = true;
    }
    if (weightsDiffer) {
      ++weightMismatch;
      if (firstWeightMismatch == SIZE_MAX) firstWeightMismatch = item;
    }
    if (indicesDiffer) {
      ++indexMismatch;
      if (firstIndexMismatch == SIZE_MAX) firstIndexMismatch = item;
    }
  }
  Log("[DEBUG-SKIN-DIFF] kind=boneWeights payload=%zu runtime=%zu "
      "compared=%zu weightMismatch=%zu indexMismatch=%zu "
      "firstWeight=%lld firstIndex=%lld maxWeightDelta=%.9g",
      payload.size(), runtime.size(), count, weightMismatch, indexMismatch,
      firstWeightMismatch == SIZE_MAX ? -1ll : (long long)firstWeightMismatch,
      firstIndexMismatch == SIZE_MAX ? -1ll : (long long)firstIndexMismatch,
      maxWeightDelta);
}

static void EiemLogBoneWeightSample(const char *kind,
                                    const std::vector<BoneWeight> &values) {
  const size_t count = (std::min)(values.size(), (size_t)3);
  for (size_t index = 0; index < count; ++index) {
    const BoneWeight &value = values[index];
    const uint8_t *raw = reinterpret_cast<const uint8_t *>(&value);
    char hex[sizeof(BoneWeight) * 2 + 1] = {};
    for (size_t byte = 0; byte < sizeof(BoneWeight); ++byte)
      sprintf_s(hex + byte * 2, sizeof(hex) - byte * 2, "%02X", raw[byte]);
    Log("[DEBUG-SKIN-SAMPLE] kind=%s index=%zu weights=%.9g,%.9g,%.9g,%.9g "
        "indices=%d,%d,%d,%d raw=%s",
        kind ? kind : "unknown", index, value.weight0, value.weight1,
        value.weight2, value.weight3, value.boneIndex0, value.boneIndex1,
        value.boneIndex2, value.boneIndex3, hex);
  }
}

static void EiemLogMatrixSample(const char *kind,
                                const std::vector<Matrix4x4> &values) {
  if (values.empty()) return;
  const Matrix4x4 &value = values.front();
  Log("[DEBUG-SKIN-SAMPLE] kind=%s index=0 "
      "m=%.9g,%.9g,%.9g,%.9g|%.9g,%.9g,%.9g,%.9g|"
      "%.9g,%.9g,%.9g,%.9g|%.9g,%.9g,%.9g,%.9g",
      kind ? kind : "unknown", value.m[0], value.m[1], value.m[2], value.m[3],
      value.m[4], value.m[5], value.m[6], value.m[7], value.m[8], value.m[9],
      value.m[10], value.m[11], value.m[12], value.m[13], value.m[14],
      value.m[15]);
}

static void EiemLogBindPoseRelations(const std::vector<Matrix4x4> &payload,
                                     const std::vector<Matrix4x4> &runtime) {
  const size_t count = (std::min)(payload.size(), runtime.size());
  size_t exactMismatch = 0;
  size_t transposeMismatch = 0;
  float exactMaxAbs = 0.0f;
  float transposeMaxAbs = 0.0f;
  for (size_t item = 0; item < count; ++item) {
    bool exactDifferent = false;
    bool transposeDifferent = false;
    for (size_t row = 0; row < 4; ++row) {
      for (size_t column = 0; column < 4; ++column) {
        const size_t component = column * 4 + row;
        const size_t transposed = row * 4 + column;
        const float exactDelta =
            std::fabs(payload[item].m[component] - runtime[item].m[component]);
        const float transposeDelta =
            std::fabs(payload[item].m[component] - runtime[item].m[transposed]);
        exactDifferent = exactDifferent || exactDelta != 0.0f;
        transposeDifferent = transposeDifferent || transposeDelta != 0.0f;
        exactMaxAbs = (std::max)(exactMaxAbs, exactDelta);
        transposeMaxAbs = (std::max)(transposeMaxAbs, transposeDelta);
      }
    }
    if (exactDifferent) ++exactMismatch;
    if (transposeDifferent) ++transposeMismatch;
  }
  Log("[DEBUG-SKIN-RELATION] kind=bindposes count=%zu exactMismatch=%zu "
      "exactMaxAbs=%.9g transposeMismatch=%zu transposeMaxAbs=%.9g",
      count, exactMismatch, exactMaxAbs, transposeMismatch, transposeMaxAbs);
}

static void EiemComparePayloadWithRuntimeMesh(
    const char *label, const EiemNativeMeshDocument &document, void *mesh) {
  if (!mesh) return;
  std::vector<Vector3> vertices;
  std::vector<BoneWeight> skin;
  std::vector<Matrix4x4> bindPoses;
  if (s_eiemMeshGetVertices)
    EiemCopyBackendArray(EiemBackendInvokeNoThrow(s_eiemMeshGetVertices, mesh),
                         &vertices);
  if (s_eiemMeshGetBoneWeights)
    EiemCopyBackendArray(
        EiemBackendInvokeNoThrow(s_eiemMeshGetBoneWeights, mesh), &skin);
  if (s_eiemMeshGetBindPoses)
    EiemCopyBackendArray(
        EiemBackendInvokeNoThrow(s_eiemMeshGetBindPoses, mesh), &bindPoses);
  Log("[DEBUG-SKIN-DIFF] mesh=%s object=%p", label ? label : "unknown", mesh);
  EiemLogArrayDiff("vertices", document.vertices, vertices,
                   document.vertices.size());
  EiemLogBoneWeightDiff(document.skin, skin, document.skin.size());
  EiemLogArrayDiff("bindposes", document.bindPoses, bindPoses,
                   document.bindPoses.size());
  EiemLogBoneWeightSample("payloadWeight", document.skin);
  EiemLogBoneWeightSample(label && strcmp(label, "source") == 0
                              ? "sourceWeight"
                              : "replacementWeight",
                          skin);
  EiemLogMatrixSample("payloadBindpose", document.bindPoses);
  EiemLogMatrixSample(label && strcmp(label, "source") == 0
                          ? "sourceBindpose"
                          : "replacementBindpose",
                      bindPoses);
  EiemLogBindPoseRelations(document.bindPoses, bindPoses);
}

static uint64_t EiemHashBytes(uint64_t hash, const void *data, size_t size) {
  const uint8_t *bytes = static_cast<const uint8_t *>(data);
  for (size_t index = 0; index < size; ++index) {
    hash ^= bytes[index];
    hash *= 1099511628211ull;
  }
  return hash;
}

static void EiemLogRendererBoneFingerprint(const char *label, void *renderer) {
  if (!renderer || !g_smr_get_bones) return;
  void *bones = EiemBackendInvokeNoThrow(g_smr_get_bones, renderer);
  const int32_t count = EiemBackendManagedArrayLength(bones);
  if (!bones || count <= 0 || count > 512) return;
  void **items = (void **)((char *)bones + IL2CPP_ARRAY_DATA);
  uint64_t references = 1469598103934665603ull;
  uint64_t matrices = 1469598103934665603ull;
  for (int32_t index = 0; index < count; ++index) {
    references = EiemHashBytes(references, &items[index], sizeof(items[index]));
    if (!items[index] || !g_transform_get_localToWorldMatrix) continue;
    void *boxed = EiemBackendInvokeNoThrow(g_transform_get_localToWorldMatrix,
                                           items[index]);
    if (boxed)
      matrices = EiemHashBytes(matrices, (char *)boxed + 16,
                               sizeof(Matrix4x4));
  }
  Log("[DEBUG-SKIN-DIFF] bones=%s renderer=%p count=%d refs=%016llX "
      "matrices=%016llX",
      label ? label : "unknown", renderer, count,
      (unsigned long long)references, (unsigned long long)matrices);
}

static void EiemLogNativeMeshSkinState(const char *label, void *mesh) {
  if (!mesh) return;
  void *weights = s_eiemMeshGetBoneWeights
                      ? Invoke(s_eiemMeshGetBoneWeights, mesh)
                      : nullptr;
  void *bindPoses = s_eiemMeshGetBindPoses
                       ? Invoke(s_eiemMeshGetBindPoses, mesh)
                       : nullptr;
  Log("[DEBUG-mesh-state] %s mesh=%p boneWeights=%d bindposes=%d",
      label ? label : "mesh", mesh,
      EiemBackendManagedArrayLength(weights),
      EiemBackendManagedArrayLength(bindPoses));
}

static uint32_t EiemBonePathCrc32(const std::string &value) {
  uint32_t crc = 0xFFFFFFFFu;
  for (unsigned char byte : value) {
    crc ^= byte;
    for (int bit = 0; bit < 8; ++bit)
      crc = (crc & 1u) ? ((crc >> 1) ^ 0xEDB88320u) : (crc >> 1);
  }
  return crc ^ 0xFFFFFFFFu;
}

static void *EiemBackendInvokeNoThrow(void *method, void *self) {
  if (!method || !self) return nullptr;
  __try { return Invoke(method, self); }
  __except (EXCEPTION_EXECUTE_HANDLER) { return nullptr; }
}

static void EiemCollectBonePathHashes(void *transform,
                                      std::vector<uint32_t> *out) {
  if (!transform || !out || !g_object_get_name) return;
  std::vector<std::string> names;
  for (void *current = transform; current && names.size() < 128;) {
    char name[192] = {};
    void *nameObject = EiemBackendInvokeNoThrow(g_object_get_name, current);
    if (nameObject) ReadStrUtf8(nameObject, name, sizeof(name));
    names.emplace_back(name[0] ? name : "<unnamed>");
    current = g_transform_get_parent
                  ? Invoke(g_transform_get_parent, current)
                  : nullptr;
  }
  // ModelConverter emits the complete path and then removes one leading
  // ancestor at a time (root/a/b -> root/a/b, a/b, b). `names` is collected
  // in the opposite direction (bone -> parent -> root), so a candidate is
  // the reverse of names[start..0]. The old implementation removed the bone
  // from the end and generated prefixes instead of the required suffixes.
  for (size_t start = names.size(); start > 0; --start) {
    std::string path;
    for (size_t index = start; index > 0; --index) {
      if (!path.empty()) path.push_back('/');
      path += names[index - 1];
    }
    out->push_back(EiemBonePathCrc32(path));
  }
}


static bool EiemWriteMeshShapes(void *mesh, const EiemNativeMeshDocument &document,
                                char *error, size_t errorSize) {
  if (document.blendShapeChannels.empty()) return true;
  auto reject = [&](const char *reason) {
    if (error) strncpy_s(error, errorSize, reason, _TRUNCATE);
    return false;
  };
  if (!s_eiemMeshAddBlendShapeFrame || !s_eiemVector3Class ||
      !g_mesh_get_blendShapeCount || !g_mesh_GetBlendShapeName ||
      !s_eiemMeshGetBlendShapeFrameCount)
    return reject("Unity BlendShape APIs are unavailable");
  for (const auto &channel : document.blendShapeChannels) {
    for (uint32_t offset = 0; offset < channel.frameCount; ++offset) {
      const uint32_t frameIndex = channel.frameIndex + offset;
      const auto &frame = document.blendShapeFrames[frameIndex];
      std::vector<Vector3> vertices(document.vertexCount), normals(document.vertexCount), tangents(document.vertexCount);
      for (uint32_t i = 0; i < frame.vertexCount; ++i) {
        const auto &vertex = document.blendShapeVertices[frame.firstVertex + i];
        if (vertex.index >= (uint32_t)document.vertexCount)
          return reject("BlendShape vertex index is outside the mesh");
        vertices[vertex.index] = vertex.vertex;
        if (frame.hasNormals) normals[vertex.index] = vertex.normal;
        if (frame.hasTangents) tangents[vertex.index] = vertex.tangent;
      }
      void *name = il2cpp_string_new(channel.name.c_str());
      float weight = document.blendShapeWeights[frameIndex];
      void *v = EiemMakeValueArray(s_eiemVector3Class, vertices);
      void *n = EiemMakeValueArray(s_eiemVector3Class, normals);
      void *t = EiemMakeValueArray(s_eiemVector3Class, tangents);
      if (!name || !v || !n || !t) return reject("Unable to allocate BlendShape arrays");
      void *result = nullptr; void *args[] = {name, &weight, v, n, t};
      if (!InvokeChecked(s_eiemMeshAddBlendShapeFrame, mesh, args, &result))
        return reject("Unity AddBlendShapeFrame failed");
    }
  }
  void *boxed = nullptr;
  if (!InvokeChecked(g_mesh_get_blendShapeCount, mesh, nullptr, &boxed) || !boxed ||
      *(int *)((char *)boxed + 16) != (int)document.blendShapeChannels.size())
    return reject("Unity BlendShape channel count does not match payload");
  for (int index = 0; index < (int)document.blendShapeChannels.size(); ++index) {
    const auto &channel = document.blendShapeChannels[index];
    void *text = nullptr; void *args[] = {&index};
    if (!InvokeChecked(g_mesh_GetBlendShapeName, mesh, args, &text) || !text)
      return reject("Unable to read Unity BlendShape channel name");
    std::vector<char> name(channel.name.size() + 2);
    ReadStrUtf8(text, name.data(), name.size());
    if (channel.name != name.data() ||
        !InvokeChecked(s_eiemMeshGetBlendShapeFrameCount, mesh, args, &boxed) || !boxed ||
        *(int *)((char *)boxed + 16) != (int)channel.frameCount)
      return reject("Unity BlendShape channel metadata does not match payload");
  }
  return true;
}

static void *EiemBuildNativeMesh(const char *path, void *templateMesh,
                                 char *error, size_t errorSize,
                                 std::shared_ptr<const EiemSkinIdentity> *skin = nullptr) {
  EiemNativeMeshDocument document;
  if (!EiemReadNativeMesh(path, &document, error, errorSize)) return nullptr;
  if (skin) {
    skin->reset();
    if (!document.skin.empty()) {
      if (document.bindPoses.size() != document.boneHashes.size()) {
        if (error) strncpy_s(error, errorSize, "Mesh bindpose/hash counts differ", _TRUNCATE);
        return nullptr;
      }
      auto identity = std::make_shared<EiemSkinIdentity>();
      identity->paths = document.bonePaths;
      identity->hashes = document.boneHashes;
      *skin = identity;
    }
  }
  EiemComparePayloadWithRuntimeMesh("source", document, templateMesh);
  Log("[DEBUG-mesh] payload path=%s vertices=%d indices=%zu submeshes=%zu "
      "normals=%zu tangents=%zu colors=%zu skin=%zu bindposes=%zu tid=%lu",
      path ? path : "<null>", document.vertexCount, document.indices.size(),
      document.subMeshes.size(), document.normals.size(),
      document.tangents.size(), document.colors.size(), document.skin.size(),
      document.bindPoses.size(), (unsigned long)GetCurrentThreadId());
  if (!s_eiemMeshClass || !s_eiemMeshCtor || !s_eiemMeshSetVertices ||
      !s_eiemMeshSetSubMeshCount || !s_eiemMeshSetTriangles ||
      !s_eiemVector3Class || !s_eiemInt32Class) {
    if (error) strncpy_s(error, errorSize, "Unity Mesh write APIs are unavailable", _TRUNCATE);
    return nullptr;
  }
  // Build a fresh Mesh and write every channel explicitly.  Cloning a source
  // Mesh is unsafe in Endfield: its native vertex-layout/cache can survive
  // the managed setters, leaving the replacement with the source vertex
  // count while its payload contains a different buffer.
  void *mesh = il2cpp_object_new(s_eiemMeshClass);
  if (!mesh) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Mesh", _TRUNCATE);
    return nullptr;
  }
  Invoke(s_eiemMeshCtor, mesh);
  // Preserve the logical sub-asset name on generated Mesh objects.  The game
  // uses this name in a few post-model paths when the serialized SubMeshInfo
  // meshName field is absent; without it the replacement can be rebound to
  // the original resource on the next LOD/skin pass.
  if (s_eiemObjectSetName && !document.name.empty()) {
    void *name = il2cpp_string_new(document.name.c_str());
    if (name) {
      void *nameParams[] = {name};
      Invoke(s_eiemObjectSetName, mesh, nameParams);
    }
  }
  Log("[DEBUG-mesh] replacement mesh=%p sourceTemplate=%p construction=fresh", mesh,
      templateMesh);
  if (document.vertices.size() > 65535 && s_eiemMeshSetIndexFormat) {
    int32_t indexFormat = 1;  // UnityEngine.Rendering.IndexFormat.UInt32
    void *params[] = {&indexFormat};
    Invoke(s_eiemMeshSetIndexFormat, mesh, params);
  }
  auto setArray = [&](void *method, void *array) {
    if (!method || !array) return false;
    void *params[] = {array};
    Invoke(method, mesh, params);
    return true;
  };
  auto setRequired = [&](void *method, void *klass, const auto &values) {
    if (values.empty()) return true;
    if (!method || !klass) return false;
    return setArray(method, EiemMakeValueArray(klass, values));
  };
  if (!setRequired(s_eiemMeshSetVertices, s_eiemVector3Class, document.vertices) ||
      !setRequired(s_eiemMeshSetNormals, s_eiemVector3Class, document.normals) ||
      !setRequired(s_eiemMeshSetTangents, s_eiemVector4Class, document.tangents) ||
      !setRequired(s_eiemMeshSetColors, s_eiemColorClass, document.colors)) {
    if (error) strncpy_s(error, errorSize, "Unable to write Unity Mesh vertex channels", _TRUNCATE);
    return nullptr;
  }
  for (int32_t channel = 0; channel < 8; ++channel) {
    const auto &uv = document.uvs[channel];
    if (uv.Empty()) continue;
    void *method = nullptr;
    void *array = nullptr;
    if (uv.dimensions == 2 && s_eiemVector2Class && s_eiemMeshSetUVs2) {
      method = s_eiemMeshSetUVs2;
      array = EiemMakeValueArray(s_eiemVector2Class, uv.values2);
    } else if (uv.dimensions == 3 && s_eiemVector3Class && s_eiemMeshSetUVs3) {
      method = s_eiemMeshSetUVs3;
      array = EiemMakeValueArray(s_eiemVector3Class, uv.values3);
    } else if (uv.dimensions == 4 && s_eiemVector4Class && s_eiemMeshSetUVs4) {
      method = s_eiemMeshSetUVs4;
      array = EiemMakeValueArray(s_eiemVector4Class, uv.values4);
    }
    if (!method || !array) {
      if (error) strncpy_s(error, errorSize, "Unity Mesh UV APIs are unavailable", _TRUNCATE);
      return nullptr;
    }
    void *params[] = {&channel, array};
    Invoke(method, mesh, params);
  }
  int32_t subMeshCount = (int32_t)document.subMeshes.size();
  void *subMeshParams[] = {&subMeshCount};
  Invoke(s_eiemMeshSetSubMeshCount, mesh, subMeshParams);
  for (int32_t index = 0; index < subMeshCount; ++index) {
    const auto &subMesh = document.subMeshes[(size_t)index];
    std::vector<int32_t> triangles;
    triangles.reserve(subMesh.indexCount);
    for (uint32_t offset = 0; offset < subMesh.indexCount; ++offset) {
      const uint32_t value = document.indices[(size_t)subMesh.indexStart + offset];
      if (value > INT32_MAX || value >= (uint32_t)document.vertexCount) {
        if (error) strncpy_s(error, errorSize, "EIEM Mesh index is outside its vertex buffer", _TRUNCATE);
        return nullptr;
      }
      triangles.push_back((int32_t)value);
    }
    void *array = EiemMakeValueArray(s_eiemInt32Class, triangles);
    if (!array) {
      if (error) strncpy_s(error, errorSize, "Unable to create Unity index array", _TRUNCATE);
      return nullptr;
    }
    void *params[] = {array, &index};
    Invoke(s_eiemMeshSetTriangles, mesh, params);
  }
  // Bind poses define the bone palette consumed by BoneWeight indices. Write
  // that palette first so Unity never observes a transient skin whose indices
  // address an empty bind-pose array.
  if (!setRequired(s_eiemMeshSetBindPoses, s_eiemMatrix4x4Class, document.bindPoses) ||
      !setRequired(s_eiemMeshSetBoneWeights, s_eiemBoneWeightClass, document.skin)) {
    if (error) strncpy_s(error, errorSize, "Unity Mesh skinning APIs are unavailable", _TRUNCATE);
    return nullptr;
  }
  if (!EiemWriteMeshShapes(mesh, document, error, errorSize)) return nullptr;
  // A newly-created Unity Mesh starts with an empty bounds volume. Without
  // recalculating it, the renderer can cull a valid replacement immediately.
  if (g_mesh_recalculateBounds)
    Invoke(g_mesh_recalculateBounds, mesh);
  // The managed channel setters update Unity's CPU-side Mesh data. Explicitly
  // submit the completed buffer so Endfield's custom skin/GPU path cannot see
  // an uninitialized native vertex buffer on its first draw.
  if (s_eiemMeshUploadMeshData) {
    bool markNoLongerReadable = false;
    void *uploadParams[] = {&markNoLongerReadable};
    Invoke(s_eiemMeshUploadMeshData, mesh, uploadParams);
  }
  if (g_mesh_get_vertexCount && g_mesh_get_subMeshCount && g_mesh_GetIndexCount) {
    auto unboxInt = [](void *boxed) -> int32_t {
      __try { return boxed ? *(int32_t *)((char *)boxed + 16) : -1; }
      __except (1) { return -1; }
    };
    const int32_t actualVertices = unboxInt(Invoke(g_mesh_get_vertexCount, mesh));
    const int32_t actualSubMeshes = unboxInt(Invoke(g_mesh_get_subMeshCount, mesh));
    int64_t actualIndices = 0;
    if (actualSubMeshes >= 0 && actualSubMeshes <= 64) {
      for (int32_t index = 0; index < actualSubMeshes; ++index) {
        void *params[] = {&index};
        const int32_t count = unboxInt(Invoke(g_mesh_GetIndexCount, mesh, params));
        if (count < 0) { actualIndices = -1; break; }
        actualIndices += count;
      }
    }
    Log("[DEBUG-mesh] Unity mesh result=%p vertices=%d submeshes=%d indices=%lld",
        mesh, actualVertices, actualSubMeshes, (long long)actualIndices);
    const bool readbackOk =
        actualVertices == document.vertexCount &&
        actualSubMeshes == (int32_t)document.subMeshes.size() &&
        actualIndices == (int64_t)document.indices.size();
    if (!readbackOk) {
      if (error) strncpy_s(error, errorSize,
                           "Unity Mesh read-back does not match EIEM payload",
                           _TRUNCATE);
      Log("[MOD] Mesh construction rejected: payload vertices=%d submeshes=%zu indices=%zu; "
          "readback vertices=%d submeshes=%d indices=%lld",
          document.vertexCount, document.subMeshes.size(), document.indices.size(),
          actualVertices, actualSubMeshes, (long long)actualIndices);
      return nullptr;
    }
  }
  EiemLogNativeMeshSkinState("result", mesh);
  EiemComparePayloadWithRuntimeMesh("replacement", document, mesh);
  if (s_eiemMeshGetBoneWeights || s_eiemMeshGetBindPoses) {
    const int32_t actualSkin = s_eiemMeshGetBoneWeights
                                   ? EiemBackendManagedArrayLength(
                                         EiemBackendInvokeNoThrow(
                                             s_eiemMeshGetBoneWeights, mesh))
                                   : -1;
    const int32_t actualBindPoses = s_eiemMeshGetBindPoses
                                        ? EiemBackendManagedArrayLength(
                                              EiemBackendInvokeNoThrow(
                                                  s_eiemMeshGetBindPoses, mesh))
                                        : -1;
    const bool skinOk =
        (document.skin.empty() || actualSkin < 0 ||
         actualSkin == (int32_t)document.skin.size()) &&
        (document.bindPoses.empty() || actualBindPoses < 0 ||
         actualBindPoses == (int32_t)document.bindPoses.size());
    if (!skinOk) {
      if (error) strncpy_s(error, errorSize,
                           "Unity Mesh skin read-back does not match EIEM payload",
                           _TRUNCATE);
      Log("[MOD] Mesh construction rejected: payload skin=%zu bindposes=%zu; "
          "readback skin=%d bindposes=%d",
          document.skin.size(), document.bindPoses.size(), actualSkin,
          actualBindPoses);
      return nullptr;
    }
  }
  Log("[DEBUG-mesh-state] expected boneWeights=%zu bindposes=%zu",
      document.skin.size(), document.bindPoses.size());
  return mesh;
}

// Temporary read-only residue probe; callbacks run only after cache locks exit.
static void (*s_eiemResourceDiagnostic)(const char *, const char *, const char *, void *) = nullptr;

static SRWLOCK s_eiemMeshResourceCacheLock = SRWLOCK_INIT;
static std::vector<EiemObjectResourceCacheEntry> s_eiemMeshResourceCache;

static uint64_t EiemMeshResourceFileStamp(const char *path) {
  if (!path || !path[0]) return 0;
  WIN32_FILE_ATTRIBUTE_DATA data = {};
  if (!GetFileAttributesExA(path, GetFileExInfoStandard, &data)) return 0;
  ULARGE_INTEGER time = {};
  time.LowPart = data.ftLastWriteTime.dwLowDateTime;
  time.HighPart = data.ftLastWriteTime.dwHighDateTime;
  return time.QuadPart ^ ((uint64_t)data.nFileSizeHigh << 32) ^ data.nFileSizeLow;
}

static void EiemClearObjectResourceCache(
    std::vector<EiemObjectResourceCacheEntry> &cache, SRWLOCK *lock) {
  if (!lock) return;
  AcquireSRWLockExclusive(lock);
  cache.clear();
  ReleaseSRWLockExclusive(lock);
}

static void EiemClearNativeMeshResourceCache() {
  AcquireSRWLockExclusive(&s_eiemMeshResourceCacheLock);
  const size_t count = s_eiemMeshResourceCache.size();
  s_eiemMeshResourceCache.clear();
  ReleaseSRWLockExclusive(&s_eiemMeshResourceCacheLock);
  EiemClearObjectResourceCache(s_eiemMaterialResourceCache,
                               &s_eiemMaterialResourceCacheLock);
  EiemClearObjectResourceCache(s_eiemTextureResourceCache,
                               &s_eiemTextureResourceCacheLock);
  if (count)
    Log("[MOD] Released %zu generated mesh resource(s)", count);
}


static bool EiemBuildMeshResource(const EiemModRule &rule, void **outMesh,
                                  char *error, size_t errorSize,
                                  void *templateMesh = nullptr,
                                  std::shared_ptr<const EiemSkinIdentity> *skin = nullptr) {
  if (outMesh) *outMesh = nullptr;
  if (!EiemOnUnityThread()) {
    if (error) strncpy_s(error, errorSize, "Mesh construction requires Unity thread", _TRUNCATE);
    return false;
  }
  EiemModResource resource = {};
  if (!rule.hasMesh || !EiemFindModResource(rule.modPath, rule.mesh, "Mesh", &resource)) {
    if (error) strncpy_s(error, errorSize, "Render mesh section is not declared", _TRUNCATE);
    return false;
  }
  const char *slash = strrchr(resource.modPath, '\\');
  char path[MAX_PATH] = {};
  if (slash)
    snprintf(path, sizeof(path), "%.*s\\%s", (int)(slash - resource.modPath),
             resource.modPath, resource.path);
  else
    strncpy_s(path, sizeof(path), resource.path, _TRUNCATE);
  char fullPath[MAX_PATH] = {};
  if (!GetFullPathNameA(path, _countof(fullPath), fullPath, nullptr))
    strncpy_s(fullPath, sizeof(fullPath), path, _TRUNCATE);
  const uint64_t fileStamp = EiemMeshResourceFileStamp(fullPath);
  void *cachedMesh = nullptr;
  if (!EiemFindCachedObject(s_eiemMeshResourceCache, &s_eiemMeshResourceCacheLock,
                           resource.modPath, resource.section, fileStamp,
                           &cachedMesh, error, errorSize, skin)) return false;
  if (cachedMesh) {
    if (s_eiemResourceDiagnostic) s_eiemResourceDiagnostic("mesh-cache-hit", resource.modPath, resource.section, cachedMesh);
    Log("[DEBUG-hr1] mesh cache hit mod=%s section=%s mesh=%p",
        resource.modPath, resource.section, cachedMesh);
    if (outMesh) *outMesh = cachedMesh;
    return true;
  }

  std::shared_ptr<const EiemSkinIdentity> identity;
  void *mesh = EiemBuildNativeMesh(fullPath, templateMesh, error, errorSize, &identity);
  if (!mesh) return false;
  if (!EiemCacheObject(s_eiemMeshResourceCache, &s_eiemMeshResourceCacheLock,
                       resource.modPath, resource.section, fileStamp, mesh,
                       error, errorSize, identity)) return false;
  if (skin) *skin = identity;
  if (outMesh) *outMesh = mesh;
  if (s_eiemResourceDiagnostic) s_eiemResourceDiagnostic("mesh-built", resource.modPath, resource.section, mesh);
  Log("[DEBUG-hr1] mesh built mod=%s section=%s mesh=%p generation=%ld",
      resource.modPath, resource.section, mesh,
      InterlockedCompareExchange(&s_eiemModGeneration, 0, 0));
  return true;
}

static bool EiemResolveResourceDiskPath(const EiemModResource &resource,
                                        char *out, size_t outSize) {
  if (!out || outSize == 0 || !resource.modPath[0] || !resource.path[0]) return false;
  const char *slash = strrchr(resource.modPath, '\\');
  char joined[MAX_PATH] = {};
  if (slash)
    snprintf(joined, sizeof(joined), "%.*s\\%s", (int)(slash - resource.modPath),
             resource.modPath, resource.path);
  else
    strncpy_s(joined, sizeof(joined), resource.path, _TRUNCATE);
  return GetFullPathNameA(joined, (DWORD)outSize, out, nullptr) != 0;
}

static bool EiemReadMaterialFile(const char *path,
                                 std::vector<std::pair<std::string, std::string>> *out,
                                 char *error, size_t errorSize) {
  std::ifstream input(path, std::ios::binary);
  if (!input) {
    if (error) strncpy_s(error, errorSize, "Unable to open EIEM material file", _TRUNCATE);
    return false;
  }
  std::string line;
  bool formatSeen = false;
  while (std::getline(input, line)) {
    if (!line.empty() && line.back() == '\r') line.pop_back();
    const size_t first = line.find_first_not_of(" \t");
    if (first == std::string::npos || line[first] == ';' || line[first] == '#') continue;
    const size_t equals = line.find('=', first);
    if (equals == std::string::npos) continue;
    std::string key = line.substr(first, equals - first);
    std::string value = line.substr(equals + 1);
    const size_t keyEnd = key.find_last_not_of(" \t");
    const size_t valueFirst = value.find_first_not_of(" \t");
    const size_t valueEnd = value.find_last_not_of(" \t");
    if (keyEnd == std::string::npos) continue;
    key.resize(keyEnd + 1);
    value = valueFirst == std::string::npos ? "" : value.substr(valueFirst, valueEnd - valueFirst + 1);
    if (_stricmp(key.c_str(), "format") == 0) formatSeen = value == "EIEMMAT";
    out->push_back({std::move(key), std::move(value)});
  }
  if (!formatSeen) {
    if (error) strncpy_s(error, errorSize, "Not an EIEMMAT file", _TRUNCATE);
    return false;
  }
  return true;
}

static uint64_t EiemMaterialDependencyStamp(
    const EiemModRule &rule, uint64_t materialStamp,
    const std::vector<std::pair<std::string, std::string>> &values) {
  // FNV-1a is sufficient here: this is a cache key, not an identity exposed
  // to users. Include every referenced texture file so a PNG-only edit
  // invalidates the cloned Material without rebuilding unrelated resources.
  uint64_t stamp = 1469598103934665603ull ^ materialStamp;
  for (const auto &pair : values) {
    if (_strnicmp(pair.first.c_str(), "texture.", 8) != 0 ||
        _strnicmp(pair.first.c_str(), "texture_scale.", 14) == 0 ||
        _strnicmp(pair.first.c_str(), "texture_offset.", 15) == 0)
      continue;
    EiemModResource texture = {};
    uint64_t dependency = 0;
    if (EiemFindModResource(rule.modPath, pair.second.c_str(), "Texture",
                            &texture)) {
      char path[MAX_PATH] = {};
      if (EiemResolveResourceDiskPath(texture, path, sizeof(path)))
        dependency = EiemTextureDependencyStamp(
            texture, EiemMeshResourceFileStamp(path));
    }
    for (const unsigned char byte : pair.second) {
      stamp ^= byte;
      stamp *= 1099511628211ull;
    }
    stamp ^= dependency;
    stamp *= 1099511628211ull;
  }
  return stamp;
}

static void *EiemLoadOriginalAsset(const char *logicalPath, void *assetClass,
                                   char *error, size_t errorSize) {
  if (!logicalPath || !logicalPath[0] || !assetClass ||
      !s_eiemResourceManagerInstance || !s_eiemResourceManagerLoad ||
      !s_eiemProxyLoadImmediate || !s_eiemProxyGet ||
      !il2cpp_object_unbox) {
    if (error) strncpy_s(error, errorSize, "Game resource loader is unavailable", _TRUNCATE);
    return nullptr;
  }
  void *managedPath = il2cpp_string_new(logicalPath);
  void *type = il2cpp_type_get_object(il2cpp_class_get_type(assetClass));
  uint8_t category = 0;  // Beyond.Resource.RootCategory.Main
  void *params[] = {managedPath, type, &category};
  void *handle = Invoke(s_eiemResourceManagerLoad,
                        s_eiemResourceManagerInstance, params);
  if (!handle) {
    if (error) strncpy_s(error, errorSize, "Game resource loader returned no handle", _TRUNCATE);
    return nullptr;
  }
  // BundleResourceManager.Load returns the value type FAssetProxyHandle.
  // il2cpp_runtime_invoke boxes value-type return values; its instance methods
  // require the address of the unboxed payload, not the Il2CppObject header.
  // Do not replace this with a fixed object-header offset: the exported IL2CPP
  // API is the authoritative ABI boundary.
  void *unboxedHandle = il2cpp_object_unbox(handle);
  if (!unboxedHandle) {
    if (error)
      strncpy_s(error, errorSize,
                "Game resource loader returned an invalid value-type handle",
                _TRUNCATE);
    return nullptr;
  }
  Invoke(s_eiemProxyLoadImmediate, unboxedHandle);
  void *asset = Invoke(s_eiemProxyGet, unboxedHandle);
  if (!asset && error)
    strncpy_s(error, errorSize, "Game resource loader could not resolve source path", _TRUNCATE);
  return asset;
}

static bool EiemParseColor(const std::string &text, Color *out) {
  if (!out) return false;
  return sscanf_s(text.c_str(), "%f,%f,%f,%f", &out->r, &out->g, &out->b, &out->a) == 4;
}

static bool EiemParseVector2(const std::string &text, Vector2 *out) {
  if (!out) return false;
  return sscanf_s(text.c_str(), "%f,%f", &out->x, &out->y) == 2;
}

static bool EiemParseFloat(const std::string &text, float *out) {
  if (!out || text.empty()) return false;
  char *end = nullptr;
  const float value = strtof(text.c_str(), &end);
  if (end == text.c_str() || !end || *end != '\0') return false;
  *out = value;
  return true;
}

static bool EiemParseInt32(const std::string &text, int32_t *out) {
  if (!out || text.empty()) return false;
  char *end = nullptr;
  const long value = strtol(text.c_str(), &end, 10);
  if (end == text.c_str() || !end || *end != '\0' ||
      value < INT32_MIN || value > INT32_MAX)
    return false;
  *out = (int32_t)value;
  return true;
}

static uint64_t EiemTextureDependencyStamp(const EiemModResource &resource,
                                           uint64_t fileStamp) {
  uint64_t stamp = 1469598103934665603ull ^ fileStamp;
  const auto mix = [&stamp](uint64_t value) {
    stamp ^= value;
    stamp *= 1099511628211ull;
  };
  mix(resource.textureLinear ? 1u : 0u);
  mix(resource.textureMipmaps ? 1u : 0u);
  mix((uint32_t)resource.textureFilter);
  mix((uint32_t)resource.textureWrap);
  mix((uint32_t)resource.textureAniso);
  uint32_t biasBits = 0;
  memcpy(&biasBits, &resource.textureMipBias, sizeof(biasBits));
  mix(biasBits);
  return stamp;
}

static bool EiemBuildTextureResource(const EiemModRule &rule, const char *section,
                                     void **outTexture, char *error,
                                     size_t errorSize) {
  if (outTexture) *outTexture = nullptr;
  if (!section || !section[0] || !s_eiemTexture2DClass || !s_eiemByteClass ||
      !s_eiemTexture2DCtor || !s_eiemImageLoad) {
    if (error) strncpy_s(error, errorSize, "Unity PNG texture APIs are unavailable", _TRUNCATE);
    return false;
  }
  EiemModResource resource = {};
  if (!EiemFindModResource(rule.modPath, section, "Texture", &resource)) {
    if (error) strncpy_s(error, errorSize, "Material texture section is not declared", _TRUNCATE);
    return false;
  }
  char texturePath[MAX_PATH] = {};
  if (!EiemResolveResourceDiskPath(resource, texturePath, sizeof(texturePath))) {
    if (error) strncpy_s(error, errorSize, "Unable to resolve EIEM texture path", _TRUNCATE);
    return false;
  }
  const uint64_t fileStamp = EiemTextureDependencyStamp(
      resource, EiemMeshResourceFileStamp(texturePath));
  void *cachedTexture = nullptr;
  if (!EiemFindCachedObject(s_eiemTextureResourceCache, &s_eiemTextureResourceCacheLock,
                           resource.modPath, resource.section, fileStamp,
                           &cachedTexture, error, errorSize)) return false;
  if (cachedTexture) {
    if (s_eiemResourceDiagnostic) s_eiemResourceDiagnostic("texture-cache-hit", resource.modPath, resource.section, cachedTexture);
    if (outTexture) *outTexture = cachedTexture;
    return true;
  }
  std::ifstream input(texturePath, std::ios::binary | std::ios::ate);
  if (!input) {
    if (error) strncpy_s(error, errorSize, "Unable to open external texture", _TRUNCATE);
    return false;
  }
  const std::streamoff length = input.tellg();
  if (length <= 0 || length > 512ll * 1024 * 1024) {
    if (error) strncpy_s(error, errorSize, "External texture size is invalid", _TRUNCATE);
    return false;
  }
  std::vector<uint8_t> bytes((size_t)length);
  input.seekg(0, std::ios::beg);
  input.read((char *)bytes.data(), length);
  if (!input.good()) {
    if (error) strncpy_s(error, errorSize, "Unable to read external texture", _TRUNCATE);
    return false;
  }
  void *managedBytes = il2cpp_array_new(s_eiemByteClass, bytes.size());
  if (!managedBytes) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate managed PNG buffer", _TRUNCATE);
    return false;
  }
  memcpy((char *)managedBytes + IL2CPP_ARRAY_DATA, bytes.data(), bytes.size());
  void *texture = il2cpp_object_new(s_eiemTexture2DClass);
  if (!texture) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Texture2D", _TRUNCATE);
    return false;
  }
  int32_t width = 2, height = 2;
  int32_t format = 4;  // UnityEngine.TextureFormat.RGBA32
  bool mipmaps = resource.textureMipmaps;
  bool linear = resource.textureLinear;
  void *ctorParams[] = {&width, &height, &format, &mipmaps, &linear};
  Invoke(s_eiemTexture2DCtor, texture, ctorParams);
  bool markNonReadable = true;
  void *loadParams[] = {texture, managedBytes, &markNonReadable};
  void *result = Invoke(s_eiemImageLoad, nullptr, loadParams);
  const bool decoded = result && *(bool *)((char *)result + 16);
  if (!decoded) {
    if (error) strncpy_s(error, errorSize, "Unity failed to decode external PNG", _TRUNCATE);
    return false;
  }
  if (!s_eiemTextureSetFilterMode || !s_eiemTextureSetWrapMode ||
      !s_eiemTextureSetAnisoLevel || !s_eiemTextureSetMipMapBias) {
    if (error) strncpy_s(error, errorSize, "Unity texture sampler APIs are unavailable", _TRUNCATE);
    return false;
  }
  if (resource.textureFilter < 0 || resource.textureFilter > 2 ||
      resource.textureWrap < 0 || resource.textureWrap > 3 ||
      resource.textureAniso < 0 || resource.textureAniso > 16) {
    if (error) strncpy_s(error, errorSize, "EIEM texture sampler values are invalid", _TRUNCATE);
    return false;
  }
  int32_t filter = resource.textureFilter;
  int32_t wrap = resource.textureWrap;
  int32_t aniso = resource.textureAniso;
  float mipBias = resource.textureMipBias;
  void *filterParams[] = {&filter};
  void *wrapParams[] = {&wrap};
  void *anisoParams[] = {&aniso};
  void *biasParams[] = {&mipBias};
  Invoke(s_eiemTextureSetFilterMode, texture, filterParams);
  Invoke(s_eiemTextureSetWrapMode, texture, wrapParams);
  Invoke(s_eiemTextureSetAnisoLevel, texture, anisoParams);
  Invoke(s_eiemTextureSetMipMapBias, texture, biasParams);
  if (s_eiemObjectSetName) {
    void *name = il2cpp_string_new(resource.targetAsset[0]
                                       ? resource.targetAsset
                                       : resource.section);
    void *nameParams[] = {name};
    Invoke(s_eiemObjectSetName, texture, nameParams);
  }
  if (!EiemCacheObject(s_eiemTextureResourceCache, &s_eiemTextureResourceCacheLock,
                       resource.modPath, resource.section, fileStamp, texture,
                       error, errorSize)) return false;
  if (outTexture) *outTexture = texture;
  if (s_eiemResourceDiagnostic) s_eiemResourceDiagnostic("texture-built", resource.modPath, resource.section, texture);
  return true;
}

static bool EiemBuildMaterialResource(const EiemModRule &rule, const char *section,
                                      void **outMaterial, char *error,
                                      size_t errorSize) {
  if (outMaterial) *outMaterial = nullptr;
  EiemModResource resource = {};
  if (!section || !section[0] ||
      !EiemFindModResource(rule.modPath, section, "Material", &resource)) {
    if (error) strncpy_s(error, errorSize, "Render material section is not declared", _TRUNCATE);
    return false;
  }
  char materialPath[MAX_PATH] = {};
  if (!EiemResolveResourceDiskPath(resource, materialPath, sizeof(materialPath))) {
    if (error) strncpy_s(error, errorSize, "Unable to resolve EIEM material path", _TRUNCATE);
    return false;
  }
  const uint64_t fileStamp = EiemMeshResourceFileStamp(materialPath);
  std::vector<std::pair<std::string, std::string>> values;
  if (!EiemReadMaterialFile(materialPath, &values, error, errorSize)) return false;
  const uint64_t dependencyStamp =
      EiemMaterialDependencyStamp(rule, fileStamp, values);
  void *cachedMaterial = nullptr;
  if (!EiemFindCachedObject(s_eiemMaterialResourceCache, &s_eiemMaterialResourceCacheLock,
                           resource.modPath, resource.section, dependencyStamp,
                           &cachedMaterial, error, errorSize)) return false;
  // Resolve configured textures even on a Material cache hit. A native texture
  // may have expired/rebuilt without any disk timestamp changing.
  std::vector<std::pair<std::string, void *>> textures;
  for (const auto &pair : values) {
    if (_strnicmp(pair.first.c_str(), "texture.", 8) != 0) continue;
    if (!s_eiemMaterialSetTexture || !s_eiemMaterialGetTexture) {
      if (error) strncpy_s(error, errorSize, "Unity Material texture APIs are unavailable", _TRUNCATE);
      return false;
    }
    void *texture = nullptr;
    if (!EiemBuildTextureResource(rule, pair.second.c_str(), &texture, error, errorSize))
      return false;
    textures.emplace_back(pair.first.substr(8), texture);
  }
  for (const auto &texture : textures) {
    if (!cachedMaterial) break;
    void *name = il2cpp_string_new(texture.first.c_str());
    void *params[] = {name};
    if (Invoke(s_eiemMaterialGetTexture, cachedMaterial, params) != texture.second) {
      Log("[MOD-CACHE] rebuild material mod=%s section=%s reason=texture binding changed",
          resource.modPath, resource.section);
      cachedMaterial = nullptr;
    }
  }
  if (cachedMaterial) {
    if (s_eiemResourceDiagnostic) s_eiemResourceDiagnostic("material-cache-hit", resource.modPath, resource.section, cachedMaterial);
    if (outMaterial) *outMaterial = cachedMaterial;
    return true;
  }
  std::string source;
  for (const auto &pair : values)
    if (_stricmp(pair.first.c_str(), "source") == 0) source = pair.second;
  if (source.empty()) {
    if (error) strncpy_s(error, errorSize, "EIEM material has no source logical path", _TRUNCATE);
    return false;
  }
  void *sourceMaterial = EiemLoadOriginalAsset(
      source.c_str(), s_eiemMaterialClass, error, errorSize);
  if (!sourceMaterial || !s_eiemMaterialClass || !s_eiemMaterialCtorCopy) return false;
  if (EiemNativeObjectStatus(sourceMaterial) != 1) {
    if (error) strncpy_s(error, errorSize, "Source Material is not natively valid", _TRUNCATE);
    return false;
  }
  void *material = il2cpp_object_new(s_eiemMaterialClass);
  if (!material) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Material", _TRUNCATE);
    return false;
  }
  void *copyParams[] = {sourceMaterial};
  Invoke(s_eiemMaterialCtorCopy, material, copyParams);
  size_t textureIndex = 0;
  for (const auto &pair : values) {
    const char *key = pair.first.c_str();
    const char *value = pair.second.c_str();
    if (_strnicmp(key, "float.", 6) == 0) {
      if (!s_eiemMaterialSetFloat) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetFloat is unavailable", _TRUNCATE);
        return false;
      }
      float scalar = 0.0f;
      if (!EiemParseFloat(pair.second, &scalar)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material float", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 6);
      void *params[] = {name, &scalar};
      Invoke(s_eiemMaterialSetFloat, material, params);
    } else if (_strnicmp(key, "int.", 4) == 0) {
      if (!s_eiemMaterialSetInt) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetInt is unavailable", _TRUNCATE);
        return false;
      }
      int32_t integer = 0;
      if (!EiemParseInt32(pair.second, &integer)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material int", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 4);
      void *params[] = {name, &integer};
      Invoke(s_eiemMaterialSetInt, material, params);
    } else if (_strnicmp(key, "value4.", 7) == 0) {
      if (!s_eiemMaterialSetColor) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetColor is unavailable", _TRUNCATE);
        return false;
      }
      Color color = {};
      if (!EiemParseColor(pair.second, &color)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material value4", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 7);
      void *params[] = {name, &color};
      Invoke(s_eiemMaterialSetColor, material, params);
    } else if (_strnicmp(key, "texture_scale.", 14) == 0) {
      if (!s_eiemMaterialSetTextureScale || !s_eiemVector2Class) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetTextureScale is unavailable", _TRUNCATE);
        return false;
      }
      Vector2 scale = {};
      if (!EiemParseVector2(pair.second, &scale)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material texture scale", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 14);
      void *params[] = {name, &scale};
      Invoke(s_eiemMaterialSetTextureScale, material, params);
    } else if (_strnicmp(key, "texture_offset.", 15) == 0) {
      if (!s_eiemMaterialSetTextureOffset || !s_eiemVector2Class) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetTextureOffset is unavailable", _TRUNCATE);
        return false;
      }
      Vector2 offset = {};
      if (!EiemParseVector2(pair.second, &offset)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material texture offset", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 15);
      void *params[] = {name, &offset};
      Invoke(s_eiemMaterialSetTextureOffset, material, params);
    } else if (_strnicmp(key, "texture.", 8) == 0) {
      void *texture = textures[textureIndex++].second;
      void *name = il2cpp_string_new(key + 8);
      void *params[] = {name, texture};
      Invoke(s_eiemMaterialSetTexture, material, params);
      void *getParams[] = {name};
      if (Invoke(s_eiemMaterialGetTexture, material, getParams) != texture) {
        if (error) strncpy_s(error, errorSize, "Unity Material texture read-back failed", _TRUNCATE);
        return false;
      }
    }
  }
  if (!EiemCacheObject(s_eiemMaterialResourceCache, &s_eiemMaterialResourceCacheLock,
                       resource.modPath, resource.section, dependencyStamp, material,
                       error, errorSize)) return false;
  if (outMaterial) *outMaterial = material;
  if (s_eiemResourceDiagnostic) s_eiemResourceDiagnostic("material-built", resource.modPath, resource.section, material);
  return true;
}

static void EiemApplySubmeshMaterialMap(const EiemModRule &rule,
                                        void **items, uint32_t count) {
  if (!items || count == 0 || rule.submeshCount == 0) return;
  std::vector<void *> original(items, items + count);
  const uint32_t limit = rule.submeshCount < count ? rule.submeshCount : count;
  for (uint32_t submesh = 0; submesh < limit; ++submesh) {
    const int32_t sourceSlot = rule.submeshSlots[submesh];
    if (sourceSlot >= 0 && (uint32_t)sourceSlot < count)
      items[submesh] = original[(size_t)sourceSlot];
  }
}

static bool EiemBuildRendererMaterials(const EiemModRule &rule, void **outArray,
                                       char *error, size_t errorSize) {
  if (outArray) *outArray = nullptr;
  if (rule.materialCount == 0) return true;
  if (!s_eiemMaterialClass) {
    if (error) strncpy_s(error, errorSize, "Unity Material class is unavailable", _TRUNCATE);
    return false;
  }
  uint32_t arrayCount = rule.materialCount;
  for (uint32_t i = 0; i < rule.materialCount; ++i) {
    if (rule.materialSlots[i] >= 0 &&
        (uint32_t)(rule.materialSlots[i] + 1) > arrayCount)
      arrayCount = (uint32_t)rule.materialSlots[i] + 1;
  }
  void *array = il2cpp_array_new(s_eiemMaterialClass, arrayCount);
  if (!array) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Material array", _TRUNCATE);
    return false;
  }
  void **items = (void **)((char *)array + IL2CPP_ARRAY_DATA);
  for (uint32_t index = 0; index < rule.materialCount; ++index) {
    const int32_t slot = rule.materialSlots[index] >= 0
                             ? rule.materialSlots[index]
                             : (int32_t)index;
    if (!EiemBuildMaterialResource(rule, rule.materials[index], &items[slot], error, errorSize))
      return false;
  }
  EiemApplySubmeshMaterialMap(rule, items, arrayCount);
  if (outArray) *outArray = array;
  return true;
}

static bool EiemBuildRendererMaterialsForSource(const EiemModRule &rule,
                                                void *sourceRenderer,
                                                void **outArray, char *error,
                                                size_t errorSize) {
  if (outArray) *outArray = nullptr;
  if (!sourceRenderer || !g_renderer_get_sharedMaterials)
    return EiemBuildRendererMaterials(rule, outArray, error, errorSize);
  void *sourceMaterials = Invoke(g_renderer_get_sharedMaterials, sourceRenderer);
  const int sourceCount = sourceMaterials ? *(int *)((char *)sourceMaterials + 24) : 0;
  int requiredCount = sourceCount;
  for (uint32_t i = 0; i < rule.materialCount; ++i) {
    const int slot = rule.materialSlots[i] >= 0 ? rule.materialSlots[i] : (int)i;
    if (slot + 1 > requiredCount) requiredCount = slot + 1;
  }
  if (rule.submeshCount > (uint32_t)requiredCount)
    requiredCount = (int)rule.submeshCount;
  if (requiredCount <= 0) return true;
  if (!s_eiemMaterialClass) {
    if (error) strncpy_s(error, errorSize, "Unity Material class is unavailable", _TRUNCATE);
    return false;
  }
  void *array = il2cpp_array_new(s_eiemMaterialClass, (size_t)requiredCount);
  if (!array) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Material array", _TRUNCATE);
    return false;
  }
  void **items = (void **)((char *)array + IL2CPP_ARRAY_DATA);
  if (sourceMaterials && sourceCount > 0)
    memcpy(items, (char *)sourceMaterials + IL2CPP_ARRAY_DATA,
           (size_t)sourceCount * sizeof(void *));
  for (uint32_t i = 0; i < rule.materialCount; ++i) {
    const int slot = rule.materialSlots[i] >= 0 ? rule.materialSlots[i] : (int)i;
    if (!EiemBuildMaterialResource(rule, rule.materials[i], &items[slot],
                                   error, errorSize))
      return false;
  }
  EiemApplySubmeshMaterialMap(rule, items, (uint32_t)requiredCount);
  if (outArray) *outArray = array;
  return true;
}
