#pragma once

#include <cstdint>
#include <cstring>
#include <fstream>
#include <limits>
#include <string>
#include <vector>

// This is the native half of the EIEM package contract. It deliberately reads
// only the stable exchange format generated by AnimeStudio/Blender; it never
// attempts to deserialize Unity asset files in the game process.
struct EiemNativeSubMesh {
  int32_t topology;
  uint32_t indexStart;
  uint32_t indexCount;
  uint32_t baseVertex;
  uint32_t firstVertex;
  uint32_t vertexCount;
};

struct EiemNativeUvChannel {
  int32_t dimensions = 0;
  std::vector<Vector2> values2;
  std::vector<Vector3> values3;
  std::vector<Vector4> values4;
  bool Empty() const {
    return values2.empty() && values3.empty() && values4.empty();
  }
};

struct EiemNativeBlendShapeVertex {
  uint32_t index = 0;
  Vector3 vertex = {};
  Vector3 normal = {};
  Vector3 tangent = {};
};

struct EiemNativeBlendShapeFrame {
  std::string name;
  uint32_t firstVertex = 0;
  uint32_t vertexCount = 0;
  bool hasNormals = false;
  bool hasTangents = false;
  bool hasAdditionalNormals = false;
};

struct EiemNativeBlendShapeChannel {
  std::string name;
  uint32_t nameHash = 0;
  uint32_t frameIndex = 0;
  uint32_t frameCount = 0;
};

struct EiemNativeMeshDocument {
  std::string coordinateSpace;
  std::string source;
  std::string name;
  int32_t vertexCount = 0;
  std::vector<Vector3> vertices;
  std::vector<Vector3> normals;
  std::vector<Vector4> tangents;
  std::vector<Color> colors;
  EiemNativeUvChannel uvs[8];
  std::vector<uint32_t> indices;
  std::vector<EiemNativeSubMesh> subMeshes;
  std::vector<BoneWeight> skin;
  std::vector<Matrix4x4> bindPoses;
  std::vector<uint32_t> boneHashes;
  std::vector<EiemNativeBlendShapeVertex> blendShapeVertices;
  std::vector<EiemNativeBlendShapeFrame> blendShapeFrames;
  std::vector<EiemNativeBlendShapeChannel> blendShapeChannels;
  std::vector<float> blendShapeWeights;
};

class EiemNativeReader {
 public:
  explicit EiemNativeReader(const char *path) : input_(path, std::ios::binary) {}

  bool Good() const { return input_.good(); }
  bool End() { return input_.peek() == std::char_traits<char>::eof(); }

  bool Bytes(void *out, size_t count) {
    if (!out || count == 0) return count == 0;
    input_.read((char *)out, (std::streamsize)count);
    return input_.good();
  }

  template <typename T>
  bool Value(T *out) {
    return Bytes(out, sizeof(T));
  }

  bool String(std::string *out) {
    if (!out) return false;
    uint32_t length = 0;
    for (int shift = 0; shift <= 28; shift += 7) {
      uint8_t byte = 0;
      if (!Value(&byte)) return false;
      length |= (uint32_t)(byte & 0x7f) << shift;
      if (!(byte & 0x80)) break;
      if (shift == 28) return false;
    }
    if (length > 4 * 1024 * 1024) return false;
    out->resize(length);
    return !length || Bytes(out->data(), length);
  }

  bool Count(uint32_t *out, uint32_t maximum = 100000000) {
    int32_t value = 0;
    if (!Value(&value) || value < 0 || (uint32_t)value > maximum) return false;
    *out = (uint32_t)value;
    return true;
  }

  bool Skip(size_t count) {
    if (count > (size_t)(std::numeric_limits<std::streamoff>::max)()) return false;
    input_.seekg((std::streamoff)count, std::ios::cur);
    return input_.good();
  }

 private:
  std::ifstream input_;
};

static bool EiemReadFloatArray(EiemNativeReader &reader,
                               std::vector<float> *out) {
  uint32_t count = 0;
  if (!reader.Count(&count)) return false;
  out->resize(count);
  return !count || reader.Bytes(out->data(), (size_t)count * sizeof(float));
}

static bool EiemReadUvChannel(EiemNativeReader &reader,
                              EiemNativeUvChannel *out,
                              int32_t vertexCount) {
  std::vector<float> values;
  if (!out || !EiemReadFloatArray(reader, &values)) return false;
  if (values.empty()) return true;
  if (vertexCount <= 0 || values.size() % (size_t)vertexCount) return false;
  const size_t dimensions = values.size() / (size_t)vertexCount;
  out->dimensions = (int32_t)dimensions;
  if (dimensions == 2) {
    out->values2.resize((size_t)vertexCount);
    memcpy(out->values2.data(), values.data(), values.size() * sizeof(float));
  } else if (dimensions == 3) {
    out->values3.resize((size_t)vertexCount);
    memcpy(out->values3.data(), values.data(), values.size() * sizeof(float));
  } else if (dimensions == 4) {
    out->values4.resize((size_t)vertexCount);
    memcpy(out->values4.data(), values.data(), values.size() * sizeof(float));
  } else {
    return false;
  }
  return true;
}

template <typename T>
static bool EiemReadTypedFloatArray(EiemNativeReader &reader,
                                    std::vector<T> *out, uint32_t components,
                                    int32_t vertexCount) {
  std::vector<float> values;
  if (!EiemReadFloatArray(reader, &values)) return false;
  if (values.empty()) {
    out->clear();
    return true;
  }
  if (vertexCount < 0 || values.size() != (size_t)vertexCount * components ||
      sizeof(T) != components * sizeof(float))
    return false;
  out->resize((size_t)vertexCount);
  memcpy(out->data(), values.data(), values.size() * sizeof(float));
  return true;
}

static bool EiemReadBlendShapes(EiemNativeReader &reader,
                                EiemNativeMeshDocument *out) {
  uint32_t count = 0;
  if (!out || !reader.Count(&count, 10000000)) return false;
  out->blendShapeVertices.resize(count);
  for (auto &vertex : out->blendShapeVertices) {
    if (!reader.Value(&vertex.index) || !reader.Value(&vertex.vertex) ||
        !reader.Value(&vertex.normal) || !reader.Value(&vertex.tangent))
      return false;
  }
  if (!reader.Count(&count, 1000000)) return false;
  out->blendShapeFrames.resize(count);
  for (uint32_t i = 0; i < count; ++i) {
    auto &frame = out->blendShapeFrames[i];
    uint8_t hasNormals = 0, hasTangents = 0, hasAdditionalNormals = 0;
    if (!reader.String(&frame.name) || !reader.Value(&frame.firstVertex) ||
        !reader.Value(&frame.vertexCount) || !reader.Value(&hasNormals) ||
        !reader.Value(&hasTangents) || !reader.Value(&hasAdditionalNormals) ||
        (uint64_t)frame.firstVertex + frame.vertexCount >
            out->blendShapeVertices.size())
      return false;
    frame.hasNormals = hasNormals != 0;
    frame.hasTangents = hasTangents != 0;
    frame.hasAdditionalNormals = hasAdditionalNormals != 0;
  }
  if (!reader.Count(&count, 1000000)) return false;
  out->blendShapeChannels.resize(count);
  for (uint32_t i = 0; i < count; ++i) {
    auto &channel = out->blendShapeChannels[i];
    if (!reader.String(&channel.name) || !reader.Value(&channel.nameHash) ||
        !reader.Value(&channel.frameIndex) || !reader.Value(&channel.frameCount) ||
        (uint64_t)channel.frameIndex + channel.frameCount >
            out->blendShapeFrames.size())
      return false;
  }
  if (!EiemReadFloatArray(reader, &out->blendShapeWeights) ||
      out->blendShapeWeights.size() != out->blendShapeFrames.size() ||
      !reader.Count(&count, 10000000))
    return false;
  return reader.Skip((size_t)count * sizeof(float) * 3);
}

static bool EiemReadNativeMesh(const char *path, EiemNativeMeshDocument *out,
                               char *error, size_t errorSize) {
  if (error && errorSize) error[0] = '\0';
  if (!path || !out) return false;
  EiemNativeReader reader(path);
  char magic[8] = {};
  int32_t version = 0;
  if (!reader.Good() || !reader.Bytes(magic, sizeof(magic)) ||
      memcmp(magic, "EIEMESH\0", sizeof(magic)) != 0 || !reader.Value(&version) ||
      version != 1 || !reader.String(&out->coordinateSpace) ||
      !reader.String(&out->source) || !reader.String(&out->name) ||
      !reader.Value(&out->vertexCount) || out->vertexCount < 0 ||
      out->vertexCount > 10000000 ||
      !EiemReadTypedFloatArray(reader, &out->vertices, 3, out->vertexCount) ||
      !EiemReadTypedFloatArray(reader, &out->normals, 3, out->vertexCount) ||
      !EiemReadTypedFloatArray(reader, &out->tangents, 4, out->vertexCount) ||
      !EiemReadTypedFloatArray(reader, &out->colors, 4, out->vertexCount)) {
    if (error) strncpy_s(error, errorSize, "Invalid EIEM mesh header or vertex channel", _TRUNCATE);
    return false;
  }
  for (size_t channel = 0; channel < _countof(out->uvs); ++channel) {
    if (!EiemReadUvChannel(reader, &out->uvs[channel], out->vertexCount)) {
      if (error) strncpy_s(error, errorSize, "Invalid EIEM UV channel", _TRUNCATE);
      return false;
    }
  }
  uint32_t count = 0;
  if (!reader.Count(&count) || count > 300000000) goto invalid;
  out->indices.resize(count);
  if (count && !reader.Bytes(out->indices.data(), (size_t)count * sizeof(uint32_t))) goto invalid;
  if (!reader.Count(&count, 1024)) goto invalid;
  out->subMeshes.resize(count);
  for (auto &subMesh : out->subMeshes) {
    if (!reader.Value(&subMesh.topology) || !reader.Value(&subMesh.indexStart) ||
        !reader.Value(&subMesh.indexCount) || !reader.Value(&subMesh.baseVertex) ||
        !reader.Value(&subMesh.firstVertex) || !reader.Value(&subMesh.vertexCount) ||
        subMesh.topology != 0 ||
        (uint64_t)subMesh.indexStart + subMesh.indexCount > out->indices.size())
      goto invalid;
  }
  if (!reader.Count(&count, 10000000)) goto invalid;
  out->skin.resize(count);
  if (count && !reader.Bytes(out->skin.data(), (size_t)count * sizeof(BoneWeight))) goto invalid;
  if (!out->skin.empty() && out->skin.size() != out->vertices.size()) goto invalid;
  if (!reader.Count(&count, 10000000)) goto invalid;
  out->bindPoses.resize(count);
  if (count && !reader.Bytes(out->bindPoses.data(), (size_t)count * sizeof(Matrix4x4))) goto invalid;
  if (!reader.Count(&count, 10000000)) goto invalid;
  out->boneHashes.resize(count);
  if (count && !reader.Bytes(out->boneHashes.data(), (size_t)count * sizeof(uint32_t))) goto invalid;
  if (!EiemReadBlendShapes(reader, out) || !reader.End()) goto invalid;
  if (out->vertices.size() != (size_t)out->vertexCount || out->subMeshes.empty()) goto invalid;
  return true;

invalid:
  if (error) strncpy_s(error, errorSize, "Invalid or unsupported EIEM mesh payload", _TRUNCATE);
  return false;
}

static void *s_eiemMeshClass = nullptr;
static void *s_eiemVector2Class = nullptr;
static void *s_eiemVector3Class = nullptr;
static void *s_eiemVector4Class = nullptr;
static void *s_eiemColorClass = nullptr;
static void *s_eiemBoneWeightClass = nullptr;
static void *s_eiemMatrix4x4Class = nullptr;
static void *s_eiemInt32Class = nullptr;
static void *s_eiemMeshCtor = nullptr;
static void *s_eiemMeshSetIndexFormat = nullptr;
static void *s_eiemMeshSetVertices = nullptr;
static void *s_eiemMeshSetNormals = nullptr;
static void *s_eiemMeshSetTangents = nullptr;
static void *s_eiemMeshSetColors = nullptr;
static void *s_eiemMeshSetUVs2 = nullptr;
static void *s_eiemMeshSetUVs3 = nullptr;
static void *s_eiemMeshSetUVs4 = nullptr;
static void *s_eiemMeshSetSubMeshCount = nullptr;
static void *s_eiemMeshSetTriangles = nullptr;
static void *s_eiemMeshSetBoneWeights = nullptr;
static void *s_eiemMeshSetBindPoses = nullptr;
static void *s_eiemMeshAddBlendShapeFrame = nullptr;
static void *s_eiemMaterialClass = nullptr;
static void *s_eiemRendererClass = nullptr;
static void *s_eiemResourceManagerClass = nullptr;
static void *s_eiemProxyHandleClass = nullptr;
static void *s_eiemMaterialCtorCopy = nullptr;
static void *s_eiemMaterialSetFloat = nullptr;
static void *s_eiemMaterialSetInt = nullptr;
static void *s_eiemMaterialSetColor = nullptr;
static void *s_eiemMaterialSetTextureScale = nullptr;
static void *s_eiemMaterialSetTextureOffset = nullptr;
static void *s_eiemRendererSetSharedMaterials = nullptr;
static void *s_eiemResourceManagerLoad = nullptr;
static void *s_eiemProxyLoadImmediate = nullptr;
static void *s_eiemProxyGet = nullptr;
static void *s_eiemTexture2DClass = nullptr;
static void *s_eiemImageConversionClass = nullptr;
static void *s_eiemByteClass = nullptr;
static void *s_eiemTexture2DCtor = nullptr;
static void *s_eiemImageLoad = nullptr;
static void *s_eiemMaterialSetTexture = nullptr;
// Updated by the game's own resource-load hook. Using that live manager keeps
// source= paths inside the original VFS/decryption/manifest pipeline.
static void *s_eiemResourceManagerInstance = nullptr;

// Mesh, material and texture resources are generated on demand. Keep their
// Unity objects rooted so repeated renderer reconciliation (F10, scene loads)
// does not clone/decode the same file over and over.
struct EiemObjectResourceCacheEntry {
  char modPath[MAX_PATH] = {};
  char section[96] = {};
  uint64_t fileStamp = 0;
  uint32_t handle = 0;
};

static SRWLOCK s_eiemMaterialResourceCacheLock = SRWLOCK_INIT;
static std::vector<EiemObjectResourceCacheEntry> s_eiemMaterialResourceCache;
static SRWLOCK s_eiemTextureResourceCacheLock = SRWLOCK_INIT;
static std::vector<EiemObjectResourceCacheEntry> s_eiemTextureResourceCache;

static uint64_t EiemMeshResourceFileStamp(const char *path);

static void *EiemFindCachedObject(
    const std::vector<EiemObjectResourceCacheEntry> &cache,
    const char *modPath, const char *section, uint64_t fileStamp) {
  if (!modPath || !section || !il2cpp_gchandle_get_target) return nullptr;
  for (const auto &entry : cache) {
    if (_stricmp(entry.modPath, modPath) != 0 ||
        _stricmp(entry.section, section) != 0 || entry.fileStamp != fileStamp)
      continue;
    void *object = entry.handle ? il2cpp_gchandle_get_target(entry.handle) : nullptr;
    if (object) return object;
  }
  return nullptr;
}

static void EiemCacheObject(std::vector<EiemObjectResourceCacheEntry> &cache,
                            SRWLOCK *lock, const char *modPath,
                            const char *section, uint64_t fileStamp,
                            void *object) {
  if (!lock || !modPath || !section || !object || !il2cpp_gchandle_new) return;
  EiemObjectResourceCacheEntry entry = {};
  strncpy_s(entry.modPath, sizeof(entry.modPath), modPath, _TRUNCATE);
  strncpy_s(entry.section, sizeof(entry.section), section, _TRUNCATE);
  entry.fileStamp = fileStamp;
  entry.handle = il2cpp_gchandle_new(object, false);
  if (!entry.handle) return;
  AcquireSRWLockExclusive(lock);
  for (auto it = cache.begin(); it != cache.end();) {
    if (_stricmp(it->modPath, modPath) == 0 &&
        _stricmp(it->section, section) == 0 && it->fileStamp != fileStamp) {
      if (it->handle && il2cpp_gchandle_free) il2cpp_gchandle_free(it->handle);
      it = cache.erase(it);
    } else {
      ++it;
    }
  }
  cache.push_back(entry);
  ReleaseSRWLockExclusive(lock);
}

static void *EiemFindMethodWithParamTypes(void *klass, const char *name,
                                           const char *const *types,
                                           int count) {
  if (!klass || !name || !types || count < 0) return nullptr;
  void *iterator = nullptr;
  void *method = nullptr;
  while ((method = il2cpp_class_get_methods(klass, &iterator))) {
    const char *methodName = il2cpp_method_get_name(method);
    if (!methodName || strcmp(methodName, name) != 0 ||
        (int)il2cpp_method_get_param_count(method) != count)
      continue;
    bool matches = true;
    for (int index = 0; index < count; ++index) {
      void *param = il2cpp_method_get_param(method, index);
      const char *typeName = param && il2cpp_type_get_name
                                 ? il2cpp_type_get_name(param)
                                 : nullptr;
      if (!typeName || strcmp(typeName, types[index]) != 0) {
        matches = false;
        break;
      }
    }
    if (matches) return method;
  }
  return nullptr;
}

static void *EiemFindMethodWithReturnType(void *klass, const char *name,
                                           const char *returnType,
                                           int paramCount) {
  if (!klass || !name || !returnType) return nullptr;
  void *iterator = nullptr;
  void *method = nullptr;
  while ((method = il2cpp_class_get_methods(klass, &iterator))) {
    const char *methodName = il2cpp_method_get_name(method);
    if (!methodName || strcmp(methodName, name) != 0 ||
        (int)il2cpp_method_get_param_count(method) != paramCount)
      continue;
    void *type = il2cpp_method_get_return_type(method);
    const char *typeName = type && il2cpp_type_get_name ? il2cpp_type_get_name(type) : nullptr;
    if (typeName && strcmp(typeName, returnType) == 0) return method;
  }
  return nullptr;
}

static void EiemResolveResourceBackend(void **assemblies, size_t assemblyCount) {
  s_eiemMeshClass = FindClass("UnityEngine", "Mesh", assemblies, assemblyCount);
  s_eiemVector2Class = FindClass("UnityEngine", "Vector2", assemblies, assemblyCount);
  s_eiemVector3Class = FindClass("UnityEngine", "Vector3", assemblies, assemblyCount);
  s_eiemVector4Class = FindClass("UnityEngine", "Vector4", assemblies, assemblyCount);
  s_eiemColorClass = FindClass("UnityEngine", "Color", assemblies, assemblyCount);
  s_eiemBoneWeightClass = FindClass("UnityEngine", "BoneWeight", assemblies, assemblyCount);
  s_eiemMatrix4x4Class = FindClass("UnityEngine", "Matrix4x4", assemblies, assemblyCount);
  s_eiemInt32Class = FindClass("System", "Int32", assemblies, assemblyCount);
  s_eiemMaterialClass = FindClass("UnityEngine", "Material", assemblies, assemblyCount);
  s_eiemRendererClass = FindClass("UnityEngine", "Renderer", assemblies, assemblyCount);
  s_eiemResourceManagerClass = FindClass("Beyond.Resource.Runtime", "BundleResourceManager",
                                         assemblies, assemblyCount);
  s_eiemProxyHandleClass = FindClass("Beyond.Resource", "FAssetProxyHandle",
                                     assemblies, assemblyCount);
  s_eiemTexture2DClass = FindClass("UnityEngine", "Texture2D", assemblies, assemblyCount);
  s_eiemImageConversionClass = FindClass("UnityEngine", "ImageConversion",
                                         assemblies, assemblyCount);
  s_eiemByteClass = FindClass("System", "Byte", assemblies, assemblyCount);
  if (s_eiemMeshClass) {
    s_eiemMeshCtor = FindMethod(s_eiemMeshClass, ".ctor", 0);
    s_eiemMeshSetIndexFormat = FindMethod(s_eiemMeshClass, "set_indexFormat", 1);
    s_eiemMeshSetVertices = FindMethod(s_eiemMeshClass, "set_vertices", 1);
    s_eiemMeshSetNormals = FindMethod(s_eiemMeshClass, "set_normals", 1);
    s_eiemMeshSetTangents = FindMethod(s_eiemMeshClass, "set_tangents", 1);
    s_eiemMeshSetColors = FindMethod(s_eiemMeshClass, "set_colors", 1);
    static const char *const setUvsTypes[] = {
        "System.Int32", "UnityEngine.Vector2[]"};
    static const char *const setUvs3Types[] = {
        "System.Int32", "UnityEngine.Vector3[]"};
    static const char *const setUvs4Types[] = {
        "System.Int32", "UnityEngine.Vector4[]"};
    static const char *const setTrianglesTypes[] = {
        "System.Int32[]", "System.Int32"};
    s_eiemMeshSetUVs2 = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetUVs", setUvsTypes, _countof(setUvsTypes));
    s_eiemMeshSetUVs3 = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetUVs", setUvs3Types, _countof(setUvs3Types));
    s_eiemMeshSetUVs4 = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetUVs", setUvs4Types, _countof(setUvs4Types));
    s_eiemMeshSetSubMeshCount = FindMethod(s_eiemMeshClass, "set_subMeshCount", 1);
    s_eiemMeshSetTriangles = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "SetTriangles", setTrianglesTypes,
        _countof(setTrianglesTypes));
    s_eiemMeshSetBoneWeights = FindMethod(s_eiemMeshClass, "set_boneWeights", 1);
    s_eiemMeshSetBindPoses = FindMethod(s_eiemMeshClass, "set_bindposes", 1);
    static const char *const blendShapeTypes[] = {
        "System.String", "System.Single", "UnityEngine.Vector3[]",
        "UnityEngine.Vector3[]", "UnityEngine.Vector3[]"};
    s_eiemMeshAddBlendShapeFrame = EiemFindMethodWithParamTypes(
        s_eiemMeshClass, "AddBlendShapeFrame", blendShapeTypes,
        _countof(blendShapeTypes));
    g_mesh_recalculateBounds = FindMethod(s_eiemMeshClass, "RecalculateBounds", 0);
  }
  if (s_eiemMaterialClass) {
    static const char *const stringFloatTypes[] = {"System.String", "System.Single"};
    static const char *const stringIntTypes[] = {"System.String", "System.Int32"};
    static const char *const stringColorTypes[] = {"System.String", "UnityEngine.Color"};
    static const char *const stringTextureTypes[] = {"System.String", "UnityEngine.Texture"};
    static const char *const stringVector2Types[] = {"System.String", "UnityEngine.Vector2"};
    s_eiemMaterialCtorCopy = FindMethod(s_eiemMaterialClass, ".ctor", 1);
    s_eiemMaterialSetFloat = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetFloat", stringFloatTypes, _countof(stringFloatTypes));
    s_eiemMaterialSetInt = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetInt", stringIntTypes, _countof(stringIntTypes));
    s_eiemMaterialSetColor = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetColor", stringColorTypes, _countof(stringColorTypes));
    s_eiemMaterialSetTexture = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetTexture", stringTextureTypes, _countof(stringTextureTypes));
    s_eiemMaterialSetTextureScale = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetTextureScale", stringVector2Types,
        _countof(stringVector2Types));
    s_eiemMaterialSetTextureOffset = EiemFindMethodWithParamTypes(
        s_eiemMaterialClass, "SetTextureOffset", stringVector2Types,
        _countof(stringVector2Types));
  }
  if (s_eiemRendererClass)
    s_eiemRendererSetSharedMaterials = FindMethod(s_eiemRendererClass, "set_sharedMaterials", 1);
  if (s_eiemResourceManagerClass) {
    static const char *const loadTypes[] = {
        "System.String", "System.Type", "Beyond.Resource.RootCategory"};
    s_eiemResourceManagerLoad = EiemFindMethodWithParamTypes(
        s_eiemResourceManagerClass, "Load", loadTypes, _countof(loadTypes));
  }
  if (s_eiemProxyHandleClass) {
    s_eiemProxyLoadImmediate = FindMethod(s_eiemProxyHandleClass, "LoadImmediate", 0);
    s_eiemProxyGet = EiemFindMethodWithReturnType(
        s_eiemProxyHandleClass, "Get", "UnityEngine.Object", 0);
  }
  if (s_eiemTexture2DClass) {
    static const char *const textureCtorTypes[] = {"System.Int32", "System.Int32"};
    s_eiemTexture2DCtor = EiemFindMethodWithParamTypes(
        s_eiemTexture2DClass, ".ctor", textureCtorTypes,
        _countof(textureCtorTypes));
  }
  if (s_eiemImageConversionClass) {
    static const char *const loadImageTypes[] = {
        "UnityEngine.Texture2D", "System.Byte[]", "System.Boolean"};
    s_eiemImageLoad = EiemFindMethodWithParamTypes(
        s_eiemImageConversionClass, "LoadImage", loadImageTypes,
        _countof(loadImageTypes));
  }
  Log("[MOD] Mesh backend: ctor=%p vertices=%p normals=%p tangents=%p uv=%p triangles=%p bones=%p bindposes=%p blendShapes=%p bounds=%p",
      s_eiemMeshCtor, s_eiemMeshSetVertices, s_eiemMeshSetNormals,
      s_eiemMeshSetTangents, s_eiemMeshSetUVs2, s_eiemMeshSetTriangles,
      s_eiemMeshSetBoneWeights, s_eiemMeshSetBindPoses,
      s_eiemMeshAddBlendShapeFrame,
      g_mesh_recalculateBounds);
  Log("[MOD] Material backend: load=%p immediate=%p get=%p clone=%p setMaterials=%p scale=%p offset=%p",
      s_eiemResourceManagerLoad, s_eiemProxyLoadImmediate, s_eiemProxyGet,
      s_eiemMaterialCtorCopy, s_eiemRendererSetSharedMaterials,
      s_eiemMaterialSetTextureScale, s_eiemMaterialSetTextureOffset);
  Log("[MOD] Texture backend: texture2D=%p imageConversion=%p loadImage=%p setTexture=%p",
      s_eiemTexture2DClass, s_eiemImageConversionClass, s_eiemImageLoad,
      s_eiemMaterialSetTexture);
}

template <typename T>
static void *EiemMakeValueArray(void *klass, const std::vector<T> &values) {
  if (!klass || values.empty()) return nullptr;
  void *array = il2cpp_array_new(klass, values.size());
  if (array) memcpy((char *)array + IL2CPP_ARRAY_DATA, values.data(),
                    values.size() * sizeof(T));
  return array;
}

static void *EiemBuildNativeMesh(const char *path, char *error, size_t errorSize) {
  EiemNativeMeshDocument document;
  if (!EiemReadNativeMesh(path, &document, error, errorSize)) return nullptr;
  if (!s_eiemMeshClass || !s_eiemMeshCtor || !s_eiemMeshSetVertices ||
      !s_eiemMeshSetSubMeshCount || !s_eiemMeshSetTriangles ||
      !s_eiemVector3Class || !s_eiemInt32Class) {
    if (error) strncpy_s(error, errorSize, "Unity Mesh write APIs are unavailable", _TRUNCATE);
    return nullptr;
  }
  void *mesh = il2cpp_object_new(s_eiemMeshClass);
  if (!mesh) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Mesh", _TRUNCATE);
    return nullptr;
  }
  Invoke(s_eiemMeshCtor, mesh);
  if (document.vertices.size() > 65535 && s_eiemMeshSetIndexFormat) {
    int32_t indexFormat = 1;  // UnityEngine.Rendering.IndexFormat.UInt32
    void *params[] = {&indexFormat};
    Invoke(s_eiemMeshSetIndexFormat, mesh, params);
  }
  auto setArray = [&](void *method, void *array) {
    if (!method || !array) return true;
    void *params[] = {array};
    Invoke(method, mesh, params);
    return true;
  };
  auto setRequired = [&](void *method, void *klass, const auto &values) {
    if (values.empty()) return true;
    if (!method || !klass) return false;
    return setArray(method, EiemMakeValueArray(klass, values));
  };
  if (!setRequired(s_eiemMeshSetVertices, s_eiemVector3Class, document.vertices) ||
      !setRequired(s_eiemMeshSetNormals, s_eiemVector3Class, document.normals) ||
      !setRequired(s_eiemMeshSetTangents, s_eiemVector4Class, document.tangents) ||
      !setRequired(s_eiemMeshSetColors, s_eiemColorClass, document.colors)) {
    if (error) strncpy_s(error, errorSize, "Unable to write Unity Mesh vertex channels", _TRUNCATE);
    return nullptr;
  }
  for (int32_t channel = 0; channel < 8; ++channel) {
    const auto &uv = document.uvs[channel];
    if (uv.Empty()) continue;
    void *method = nullptr;
    void *array = nullptr;
    if (uv.dimensions == 2 && s_eiemVector2Class && s_eiemMeshSetUVs2) {
      method = s_eiemMeshSetUVs2;
      array = EiemMakeValueArray(s_eiemVector2Class, uv.values2);
    } else if (uv.dimensions == 3 && s_eiemVector3Class && s_eiemMeshSetUVs3) {
      method = s_eiemMeshSetUVs3;
      array = EiemMakeValueArray(s_eiemVector3Class, uv.values3);
    } else if (uv.dimensions == 4 && s_eiemVector4Class && s_eiemMeshSetUVs4) {
      method = s_eiemMeshSetUVs4;
      array = EiemMakeValueArray(s_eiemVector4Class, uv.values4);
    }
    if (!method || !array) {
      if (error) strncpy_s(error, errorSize, "Unity Mesh UV APIs are unavailable", _TRUNCATE);
      return nullptr;
    }
    void *params[] = {&channel, array};
    Invoke(method, mesh, params);
  }
  int32_t subMeshCount = (int32_t)document.subMeshes.size();
  void *subMeshParams[] = {&subMeshCount};
  Invoke(s_eiemMeshSetSubMeshCount, mesh, subMeshParams);
  for (int32_t index = 0; index < subMeshCount; ++index) {
    const auto &subMesh = document.subMeshes[(size_t)index];
    std::vector<int32_t> triangles;
    triangles.reserve(subMesh.indexCount);
    for (uint32_t offset = 0; offset < subMesh.indexCount; ++offset) {
      const uint32_t value = document.indices[(size_t)subMesh.indexStart + offset];
      if (value > INT32_MAX || value >= (uint32_t)document.vertexCount) {
        if (error) strncpy_s(error, errorSize, "EIEM Mesh index is outside its vertex buffer", _TRUNCATE);
        return nullptr;
      }
      triangles.push_back((int32_t)value);
    }
    void *array = EiemMakeValueArray(s_eiemInt32Class, triangles);
    if (!array) {
      if (error) strncpy_s(error, errorSize, "Unable to create Unity index array", _TRUNCATE);
      return nullptr;
    }
    void *params[] = {array, &index};
    Invoke(s_eiemMeshSetTriangles, mesh, params);
  }
  if (!setRequired(s_eiemMeshSetBoneWeights, s_eiemBoneWeightClass, document.skin) ||
      !setRequired(s_eiemMeshSetBindPoses, s_eiemMatrix4x4Class, document.bindPoses)) {
    if (error) strncpy_s(error, errorSize, "Unity Mesh skinning APIs are unavailable", _TRUNCATE);
    return nullptr;
  }
  if (!document.blendShapeChannels.empty()) {
    if (!s_eiemMeshAddBlendShapeFrame || !s_eiemVector3Class) {
      if (error) strncpy_s(error, errorSize,
                           "Unity BlendShape APIs are unavailable", _TRUNCATE);
      return nullptr;
    }
    for (const auto &channel : document.blendShapeChannels) {
      for (uint32_t frameOffset = 0; frameOffset < channel.frameCount;
           ++frameOffset) {
        const uint32_t frameIndex = channel.frameIndex + frameOffset;
        const auto &frame = document.blendShapeFrames[frameIndex];
        std::vector<Vector3> deltaVertices((size_t)document.vertexCount);
        std::vector<Vector3> deltaNormals((size_t)document.vertexCount);
        std::vector<Vector3> deltaTangents((size_t)document.vertexCount);
        for (uint32_t i = 0; i < frame.vertexCount; ++i) {
          const auto &vertex = document.blendShapeVertices[frame.firstVertex + i];
          if (vertex.index >= (uint32_t)document.vertexCount) {
            if (error) strncpy_s(error, errorSize,
                                 "BlendShape vertex index is outside the mesh",
                                 _TRUNCATE);
            return nullptr;
          }
          deltaVertices[vertex.index] = vertex.vertex;
          if (frame.hasNormals) deltaNormals[vertex.index] = vertex.normal;
          if (frame.hasTangents) deltaTangents[vertex.index] = vertex.tangent;
        }
        void *name = il2cpp_string_new(channel.name.c_str());
        float weight = document.blendShapeWeights[frameIndex];
        void *verticesArray = EiemMakeValueArray(s_eiemVector3Class, deltaVertices);
        void *normalsArray = EiemMakeValueArray(s_eiemVector3Class, deltaNormals);
        void *tangentsArray = EiemMakeValueArray(s_eiemVector3Class, deltaTangents);
        if (!verticesArray || !normalsArray || !tangentsArray) {
          if (error) strncpy_s(error, errorSize,
                               "Unable to allocate BlendShape arrays", _TRUNCATE);
          return nullptr;
        }
        void *params[] = {name, &weight, verticesArray, normalsArray, tangentsArray};
        Invoke(s_eiemMeshAddBlendShapeFrame, mesh, params);
      }
    }
  }
  // A newly-created Unity Mesh starts with an empty bounds volume. Without
  // recalculating it, the renderer can cull a valid replacement immediately.
  if (g_mesh_recalculateBounds)
    Invoke(g_mesh_recalculateBounds, mesh);
  return mesh;
}

struct EiemMeshResourceCacheEntry {
  char modPath[MAX_PATH] = {};
  char section[96] = {};
  uint64_t fileStamp = 0;
  uint32_t handle = 0;
};

static SRWLOCK s_eiemMeshResourceCacheLock = SRWLOCK_INIT;
static std::vector<EiemMeshResourceCacheEntry> s_eiemMeshResourceCache;

static uint64_t EiemMeshResourceFileStamp(const char *path) {
  if (!path || !path[0]) return 0;
  WIN32_FILE_ATTRIBUTE_DATA data = {};
  if (!GetFileAttributesExA(path, GetFileExInfoStandard, &data)) return 0;
  ULARGE_INTEGER time = {};
  time.LowPart = data.ftLastWriteTime.dwLowDateTime;
  time.HighPart = data.ftLastWriteTime.dwHighDateTime;
  return time.QuadPart ^ ((uint64_t)data.nFileSizeHigh << 32) ^ data.nFileSizeLow;
}

static void EiemClearObjectResourceCache(
    std::vector<EiemObjectResourceCacheEntry> &cache, SRWLOCK *lock) {
  if (!lock) return;
  AcquireSRWLockExclusive(lock);
  for (const auto &entry : cache)
    if (entry.handle && il2cpp_gchandle_free) il2cpp_gchandle_free(entry.handle);
  cache.clear();
  ReleaseSRWLockExclusive(lock);
}

static void EiemClearNativeMeshResourceCache() {
  AcquireSRWLockExclusive(&s_eiemMeshResourceCacheLock);
  const size_t count = s_eiemMeshResourceCache.size();
  for (const auto &entry : s_eiemMeshResourceCache)
    if (entry.handle && il2cpp_gchandle_free)
      il2cpp_gchandle_free(entry.handle);
  s_eiemMeshResourceCache.clear();
  ReleaseSRWLockExclusive(&s_eiemMeshResourceCacheLock);
  EiemClearObjectResourceCache(s_eiemMaterialResourceCache,
                               &s_eiemMaterialResourceCacheLock);
  EiemClearObjectResourceCache(s_eiemTextureResourceCache,
                               &s_eiemTextureResourceCacheLock);
  if (count)
    Log("[MOD] Released %zu generated mesh resource(s)", count);
}

static bool EiemBuildMeshResource(const EiemModRule &rule, void **outMesh,
                                  char *error, size_t errorSize) {
  if (outMesh) *outMesh = nullptr;
  EiemModResource resource = {};
  if (!rule.hasMesh || !EiemFindModResource(rule.modPath, rule.mesh, "Mesh", &resource)) {
    if (error) strncpy_s(error, errorSize, "Render mesh section is not declared", _TRUNCATE);
    return false;
  }
  const char *slash = strrchr(resource.modPath, '\\');
  char path[MAX_PATH] = {};
  if (slash)
    snprintf(path, sizeof(path), "%.*s\\%s", (int)(slash - resource.modPath),
             resource.modPath, resource.path);
  else
    strncpy_s(path, sizeof(path), resource.path, _TRUNCATE);
  char fullPath[MAX_PATH] = {};
  if (!GetFullPathNameA(path, _countof(fullPath), fullPath, nullptr))
    strncpy_s(fullPath, sizeof(fullPath), path, _TRUNCATE);
  const uint64_t fileStamp = EiemMeshResourceFileStamp(fullPath);
  AcquireSRWLockExclusive(&s_eiemMeshResourceCacheLock);
  for (auto it = s_eiemMeshResourceCache.begin();
       it != s_eiemMeshResourceCache.end();) {
    const auto &entry = *it;
    if (_stricmp(entry.modPath, resource.modPath) != 0 ||
        _stricmp(entry.section, resource.section) != 0) {
      ++it;
      continue;
    }
    if (entry.fileStamp != fileStamp) {
      // F10 restores every renderer before this path is reached, so an old
      // generation cannot still reference the changed generated Mesh.
      if (entry.handle && il2cpp_gchandle_free)
        il2cpp_gchandle_free(entry.handle);
      it = s_eiemMeshResourceCache.erase(it);
      continue;
    }
    void *cached = il2cpp_gchandle_get_target
                       ? il2cpp_gchandle_get_target(entry.handle)
                       : nullptr;
    ReleaseSRWLockExclusive(&s_eiemMeshResourceCacheLock);
    if (cached) {
      Log("[DEBUG-hr1] mesh cache hit mod=%s section=%s mesh=%p handle=%u",
          resource.modPath, resource.section, cached, entry.handle);
      if (outMesh) *outMesh = cached;
      return true;
    }
    ++it;
  }
  ReleaseSRWLockExclusive(&s_eiemMeshResourceCacheLock);

  void *mesh = EiemBuildNativeMesh(fullPath, error, errorSize);
  if (!mesh) return false;
  uint32_t cacheHandle = 0;
  if (il2cpp_gchandle_new && il2cpp_gchandle_get_target) {
    EiemMeshResourceCacheEntry entry = {};
    strncpy_s(entry.modPath, sizeof(entry.modPath), resource.modPath, _TRUNCATE);
    strncpy_s(entry.section, sizeof(entry.section), resource.section, _TRUNCATE);
    entry.fileStamp = fileStamp;
    entry.handle = il2cpp_gchandle_new(mesh, false);
    cacheHandle = entry.handle;
    if (entry.handle) {
      AcquireSRWLockExclusive(&s_eiemMeshResourceCacheLock);
      s_eiemMeshResourceCache.push_back(entry);
      ReleaseSRWLockExclusive(&s_eiemMeshResourceCacheLock);
    }
  }
  if (outMesh) *outMesh = mesh;
  Log("[DEBUG-hr1] mesh built mod=%s section=%s mesh=%p handle=%u generation=%ld",
      resource.modPath, resource.section, mesh,
      cacheHandle, InterlockedCompareExchange(&s_eiemModGeneration, 0, 0));
  return true;
}

static bool EiemResolveResourceDiskPath(const EiemModResource &resource,
                                        char *out, size_t outSize) {
  if (!out || outSize == 0 || !resource.modPath[0] || !resource.path[0]) return false;
  const char *slash = strrchr(resource.modPath, '\\');
  char joined[MAX_PATH] = {};
  if (slash)
    snprintf(joined, sizeof(joined), "%.*s\\%s", (int)(slash - resource.modPath),
             resource.modPath, resource.path);
  else
    strncpy_s(joined, sizeof(joined), resource.path, _TRUNCATE);
  return GetFullPathNameA(joined, (DWORD)outSize, out, nullptr) != 0;
}

static bool EiemReadMaterialFile(const char *path,
                                 std::vector<std::pair<std::string, std::string>> *out,
                                 char *error, size_t errorSize) {
  std::ifstream input(path, std::ios::binary);
  if (!input) {
    if (error) strncpy_s(error, errorSize, "Unable to open EIEM material file", _TRUNCATE);
    return false;
  }
  std::string line;
  bool formatSeen = false;
  while (std::getline(input, line)) {
    if (!line.empty() && line.back() == '\r') line.pop_back();
    const size_t first = line.find_first_not_of(" \t");
    if (first == std::string::npos || line[first] == ';' || line[first] == '#') continue;
    const size_t equals = line.find('=', first);
    if (equals == std::string::npos) continue;
    std::string key = line.substr(first, equals - first);
    std::string value = line.substr(equals + 1);
    const size_t keyEnd = key.find_last_not_of(" \t");
    const size_t valueFirst = value.find_first_not_of(" \t");
    const size_t valueEnd = value.find_last_not_of(" \t");
    if (keyEnd == std::string::npos) continue;
    key.resize(keyEnd + 1);
    value = valueFirst == std::string::npos ? "" : value.substr(valueFirst, valueEnd - valueFirst + 1);
    if (_stricmp(key.c_str(), "format") == 0) formatSeen = value == "EIEMMAT";
    out->push_back({std::move(key), std::move(value)});
  }
  if (!formatSeen) {
    if (error) strncpy_s(error, errorSize, "Not an EIEMMAT file", _TRUNCATE);
    return false;
  }
  return true;
}

static uint64_t EiemMaterialDependencyStamp(
    const EiemModRule &rule, uint64_t materialStamp,
    const std::vector<std::pair<std::string, std::string>> &values) {
  // FNV-1a is sufficient here: this is a cache key, not an identity exposed
  // to users. Include every referenced texture file so a PNG-only edit
  // invalidates the cloned Material without rebuilding unrelated resources.
  uint64_t stamp = 1469598103934665603ull ^ materialStamp;
  for (const auto &pair : values) {
    if (_strnicmp(pair.first.c_str(), "texture.", 8) != 0 ||
        _strnicmp(pair.first.c_str(), "texture_scale.", 14) == 0 ||
        _strnicmp(pair.first.c_str(), "texture_offset.", 15) == 0)
      continue;
    EiemModResource texture = {};
    uint64_t dependency = 0;
    if (EiemFindModResource(rule.modPath, pair.second.c_str(), "Texture",
                            &texture)) {
      char path[MAX_PATH] = {};
      if (EiemResolveResourceDiskPath(texture, path, sizeof(path)))
        dependency = EiemMeshResourceFileStamp(path);
    }
    for (const unsigned char byte : pair.second) {
      stamp ^= byte;
      stamp *= 1099511628211ull;
    }
    stamp ^= dependency;
    stamp *= 1099511628211ull;
  }
  return stamp;
}

static void *EiemLoadOriginalAsset(const char *logicalPath, void *assetClass,
                                   char *error, size_t errorSize) {
  if (!logicalPath || !logicalPath[0] || !assetClass ||
      !s_eiemResourceManagerInstance || !s_eiemResourceManagerLoad ||
      !s_eiemProxyLoadImmediate || !s_eiemProxyGet) {
    if (error) strncpy_s(error, errorSize, "Game resource loader is unavailable", _TRUNCATE);
    return nullptr;
  }
  void *managedPath = il2cpp_string_new(logicalPath);
  void *type = il2cpp_type_get_object(il2cpp_class_get_type(assetClass));
  uint8_t category = 0;  // Beyond.Resource.RootCategory.Main
  void *params[] = {managedPath, type, &category};
  void *handle = Invoke(s_eiemResourceManagerLoad, s_eiemResourceManagerInstance, params);
  if (!handle) {
    if (error) strncpy_s(error, errorSize, "Game resource loader returned no handle", _TRUNCATE);
    return nullptr;
  }
  Invoke(s_eiemProxyLoadImmediate, handle);
  void *asset = Invoke(s_eiemProxyGet, handle);
  if (!asset && error)
    strncpy_s(error, errorSize, "Game resource loader could not resolve source path", _TRUNCATE);
  return asset;
}

static bool EiemParseColor(const std::string &text, Color *out) {
  if (!out) return false;
  return sscanf_s(text.c_str(), "%f,%f,%f,%f", &out->r, &out->g, &out->b, &out->a) == 4;
}

static bool EiemParseVector2(const std::string &text, Vector2 *out) {
  if (!out) return false;
  return sscanf_s(text.c_str(), "%f,%f", &out->x, &out->y) == 2;
}

static bool EiemParseFloat(const std::string &text, float *out) {
  if (!out || text.empty()) return false;
  char *end = nullptr;
  const float value = strtof(text.c_str(), &end);
  if (end == text.c_str() || !end || *end != '\0') return false;
  *out = value;
  return true;
}

static bool EiemParseInt32(const std::string &text, int32_t *out) {
  if (!out || text.empty()) return false;
  char *end = nullptr;
  const long value = strtol(text.c_str(), &end, 10);
  if (end == text.c_str() || !end || *end != '\0' ||
      value < INT32_MIN || value > INT32_MAX)
    return false;
  *out = (int32_t)value;
  return true;
}

static bool EiemBuildTextureResource(const EiemModRule &rule, const char *section,
                                     void **outTexture, char *error,
                                     size_t errorSize) {
  if (outTexture) *outTexture = nullptr;
  if (!section || !section[0] || !s_eiemTexture2DClass || !s_eiemByteClass ||
      !s_eiemTexture2DCtor || !s_eiemImageLoad) {
    if (error) strncpy_s(error, errorSize, "Unity PNG texture APIs are unavailable", _TRUNCATE);
    return false;
  }
  EiemModResource resource = {};
  if (!EiemFindModResource(rule.modPath, section, "Texture", &resource)) {
    if (error) strncpy_s(error, errorSize, "Material texture section is not declared", _TRUNCATE);
    return false;
  }
  char texturePath[MAX_PATH] = {};
  if (!EiemResolveResourceDiskPath(resource, texturePath, sizeof(texturePath))) {
    if (error) strncpy_s(error, errorSize, "Unable to resolve EIEM texture path", _TRUNCATE);
    return false;
  }
  const uint64_t fileStamp = EiemMeshResourceFileStamp(texturePath);
  AcquireSRWLockShared(&s_eiemTextureResourceCacheLock);
  void *cachedTexture = EiemFindCachedObject(s_eiemTextureResourceCache,
                                             resource.modPath, resource.section,
                                             fileStamp);
  ReleaseSRWLockShared(&s_eiemTextureResourceCacheLock);
  if (cachedTexture) {
    if (outTexture) *outTexture = cachedTexture;
    return true;
  }
  std::ifstream input(texturePath, std::ios::binary | std::ios::ate);
  if (!input) {
    if (error) strncpy_s(error, errorSize, "Unable to open external texture", _TRUNCATE);
    return false;
  }
  const std::streamoff length = input.tellg();
  if (length <= 0 || length > 512ll * 1024 * 1024) {
    if (error) strncpy_s(error, errorSize, "External texture size is invalid", _TRUNCATE);
    return false;
  }
  std::vector<uint8_t> bytes((size_t)length);
  input.seekg(0, std::ios::beg);
  input.read((char *)bytes.data(), length);
  if (!input.good()) {
    if (error) strncpy_s(error, errorSize, "Unable to read external texture", _TRUNCATE);
    return false;
  }
  void *managedBytes = il2cpp_array_new(s_eiemByteClass, bytes.size());
  if (!managedBytes) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate managed PNG buffer", _TRUNCATE);
    return false;
  }
  memcpy((char *)managedBytes + IL2CPP_ARRAY_DATA, bytes.data(), bytes.size());
  void *texture = il2cpp_object_new(s_eiemTexture2DClass);
  if (!texture) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Texture2D", _TRUNCATE);
    return false;
  }
  int32_t width = 2, height = 2;
  void *ctorParams[] = {&width, &height};
  Invoke(s_eiemTexture2DCtor, texture, ctorParams);
  bool markNonReadable = false;
  void *loadParams[] = {texture, managedBytes, &markNonReadable};
  void *result = Invoke(s_eiemImageLoad, nullptr, loadParams);
  if (!result) {
    if (error) strncpy_s(error, errorSize, "Unity failed to decode external PNG", _TRUNCATE);
    return false;
  }
  if (outTexture) *outTexture = texture;
  EiemCacheObject(s_eiemTextureResourceCache, &s_eiemTextureResourceCacheLock,
                  resource.modPath, resource.section, fileStamp, texture);
  return true;
}

static bool EiemBuildMaterialResource(const EiemModRule &rule, const char *section,
                                      void **outMaterial, char *error,
                                      size_t errorSize) {
  if (outMaterial) *outMaterial = nullptr;
  EiemModResource resource = {};
  if (!section || !section[0] ||
      !EiemFindModResource(rule.modPath, section, "Material", &resource)) {
    if (error) strncpy_s(error, errorSize, "Render material section is not declared", _TRUNCATE);
    return false;
  }
  char materialPath[MAX_PATH] = {};
  if (!EiemResolveResourceDiskPath(resource, materialPath, sizeof(materialPath))) {
    if (error) strncpy_s(error, errorSize, "Unable to resolve EIEM material path", _TRUNCATE);
    return false;
  }
  const uint64_t fileStamp = EiemMeshResourceFileStamp(materialPath);
  std::vector<std::pair<std::string, std::string>> values;
  if (!EiemReadMaterialFile(materialPath, &values, error, errorSize)) return false;
  const uint64_t dependencyStamp =
      EiemMaterialDependencyStamp(rule, fileStamp, values);
  AcquireSRWLockShared(&s_eiemMaterialResourceCacheLock);
  void *cachedMaterial = EiemFindCachedObject(s_eiemMaterialResourceCache,
                                              resource.modPath, resource.section,
                                              dependencyStamp);
  ReleaseSRWLockShared(&s_eiemMaterialResourceCacheLock);
  if (cachedMaterial) {
    if (outMaterial) *outMaterial = cachedMaterial;
    return true;
  }
  std::string source;
  for (const auto &pair : values)
    if (_stricmp(pair.first.c_str(), "source") == 0) source = pair.second;
  if (source.empty()) {
    if (error) strncpy_s(error, errorSize, "EIEM material has no source logical path", _TRUNCATE);
    return false;
  }
  void *sourceMaterial = EiemLoadOriginalAsset(source.c_str(), s_eiemMaterialClass, error, errorSize);
  if (!sourceMaterial || !s_eiemMaterialClass || !s_eiemMaterialCtorCopy) return false;
  void *material = il2cpp_object_new(s_eiemMaterialClass);
  if (!material) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Material", _TRUNCATE);
    return false;
  }
  void *copyParams[] = {sourceMaterial};
  Invoke(s_eiemMaterialCtorCopy, material, copyParams);
  for (const auto &pair : values) {
    const char *key = pair.first.c_str();
    const char *value = pair.second.c_str();
    if (_strnicmp(key, "float.", 6) == 0) {
      if (!s_eiemMaterialSetFloat) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetFloat is unavailable", _TRUNCATE);
        return false;
      }
      float scalar = 0.0f;
      if (!EiemParseFloat(pair.second, &scalar)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material float", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 6);
      void *params[] = {name, &scalar};
      Invoke(s_eiemMaterialSetFloat, material, params);
    } else if (_strnicmp(key, "int.", 4) == 0) {
      if (!s_eiemMaterialSetInt) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetInt is unavailable", _TRUNCATE);
        return false;
      }
      int32_t integer = 0;
      if (!EiemParseInt32(pair.second, &integer)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material int", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 4);
      void *params[] = {name, &integer};
      Invoke(s_eiemMaterialSetInt, material, params);
    } else if (_strnicmp(key, "value4.", 7) == 0) {
      if (!s_eiemMaterialSetColor) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetColor is unavailable", _TRUNCATE);
        return false;
      }
      Color color = {};
      if (!EiemParseColor(pair.second, &color)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material value4", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 7);
      void *params[] = {name, &color};
      Invoke(s_eiemMaterialSetColor, material, params);
    } else if (_strnicmp(key, "texture_scale.", 14) == 0) {
      if (!s_eiemMaterialSetTextureScale || !s_eiemVector2Class) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetTextureScale is unavailable", _TRUNCATE);
        return false;
      }
      Vector2 scale = {};
      if (!EiemParseVector2(pair.second, &scale)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material texture scale", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 14);
      void *params[] = {name, &scale};
      Invoke(s_eiemMaterialSetTextureScale, material, params);
    } else if (_strnicmp(key, "texture_offset.", 15) == 0) {
      if (!s_eiemMaterialSetTextureOffset || !s_eiemVector2Class) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetTextureOffset is unavailable", _TRUNCATE);
        return false;
      }
      Vector2 offset = {};
      if (!EiemParseVector2(pair.second, &offset)) {
        if (error) strncpy_s(error, errorSize, "Invalid EIEM material texture offset", _TRUNCATE);
        return false;
      }
      void *name = il2cpp_string_new(key + 15);
      void *params[] = {name, &offset};
      Invoke(s_eiemMaterialSetTextureOffset, material, params);
    } else if (_strnicmp(key, "texture.", 8) == 0) {
      if (!s_eiemMaterialSetTexture) {
        if (error) strncpy_s(error, errorSize, "Unity Material.SetTexture is unavailable", _TRUNCATE);
        return false;
      }
      void *texture = nullptr;
      if (!EiemBuildTextureResource(rule, value, &texture, error, errorSize))
        return false;
      void *name = il2cpp_string_new(key + 8);
      void *params[] = {name, texture};
      Invoke(s_eiemMaterialSetTexture, material, params);
    }
  }
  if (outMaterial) *outMaterial = material;
  EiemCacheObject(s_eiemMaterialResourceCache, &s_eiemMaterialResourceCacheLock,
                  resource.modPath, resource.section, dependencyStamp, material);
  return true;
}

static void EiemApplySubmeshMaterialMap(const EiemModRule &rule,
                                        void **items, uint32_t count) {
  if (!items || count == 0 || rule.submeshCount == 0) return;
  std::vector<void *> original(items, items + count);
  const uint32_t limit = rule.submeshCount < count ? rule.submeshCount : count;
  for (uint32_t submesh = 0; submesh < limit; ++submesh) {
    const int32_t sourceSlot = rule.submeshSlots[submesh];
    if (sourceSlot >= 0 && (uint32_t)sourceSlot < count)
      items[submesh] = original[(size_t)sourceSlot];
  }
}

static bool EiemBuildRendererMaterials(const EiemModRule &rule, void **outArray,
                                       char *error, size_t errorSize) {
  if (outArray) *outArray = nullptr;
  if (rule.materialCount == 0) return true;
  if (!s_eiemMaterialClass) {
    if (error) strncpy_s(error, errorSize, "Unity Material class is unavailable", _TRUNCATE);
    return false;
  }
  uint32_t arrayCount = rule.materialCount;
  for (uint32_t i = 0; i < rule.materialCount; ++i) {
    if (rule.materialSlots[i] >= 0 &&
        (uint32_t)(rule.materialSlots[i] + 1) > arrayCount)
      arrayCount = (uint32_t)rule.materialSlots[i] + 1;
  }
  void *array = il2cpp_array_new(s_eiemMaterialClass, arrayCount);
  if (!array) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Material array", _TRUNCATE);
    return false;
  }
  void **items = (void **)((char *)array + IL2CPP_ARRAY_DATA);
  for (uint32_t index = 0; index < rule.materialCount; ++index) {
    const int32_t slot = rule.materialSlots[index] >= 0
                             ? rule.materialSlots[index]
                             : (int32_t)index;
    if (!EiemBuildMaterialResource(rule, rule.materials[index], &items[slot], error, errorSize))
      return false;
  }
  EiemApplySubmeshMaterialMap(rule, items, arrayCount);
  if (outArray) *outArray = array;
  return true;
}

static bool EiemBuildRendererMaterialsForSource(const EiemModRule &rule,
                                                void *sourceRenderer,
                                                void **outArray, char *error,
                                                size_t errorSize) {
  if (outArray) *outArray = nullptr;
  if (!sourceRenderer || !g_renderer_get_sharedMaterials)
    return EiemBuildRendererMaterials(rule, outArray, error, errorSize);
  void *sourceMaterials = Invoke(g_renderer_get_sharedMaterials, sourceRenderer);
  const int sourceCount = sourceMaterials ? *(int *)((char *)sourceMaterials + 24) : 0;
  int requiredCount = sourceCount;
  for (uint32_t i = 0; i < rule.materialCount; ++i) {
    const int slot = rule.materialSlots[i] >= 0 ? rule.materialSlots[i] : (int)i;
    if (slot + 1 > requiredCount) requiredCount = slot + 1;
  }
  if (rule.submeshCount > (uint32_t)requiredCount)
    requiredCount = (int)rule.submeshCount;
  if (requiredCount <= 0) return true;
  if (!s_eiemMaterialClass) {
    if (error) strncpy_s(error, errorSize, "Unity Material class is unavailable", _TRUNCATE);
    return false;
  }
  void *array = il2cpp_array_new(s_eiemMaterialClass, (size_t)requiredCount);
  if (!array) {
    if (error) strncpy_s(error, errorSize, "Unable to allocate Unity Material array", _TRUNCATE);
    return false;
  }
  void **items = (void **)((char *)array + IL2CPP_ARRAY_DATA);
  if (sourceMaterials && sourceCount > 0)
    memcpy(items, (char *)sourceMaterials + IL2CPP_ARRAY_DATA,
           (size_t)sourceCount * sizeof(void *));
  for (uint32_t i = 0; i < rule.materialCount; ++i) {
    const int slot = rule.materialSlots[i] >= 0 ? rule.materialSlots[i] : (int)i;
    if (!EiemBuildMaterialResource(rule, rule.materials[i], &items[slot],
                                   error, errorSize))
      return false;
  }
  EiemApplySubmeshMaterialMap(rule, items, (uint32_t)requiredCount);
  if (outArray) *outArray = array;
  return true;
}
